### ISSUE TITLE
provide a carot for screen reader access

### ISSUE THREAD

**Issue by coffeeking** [mate-desktop/atril#101]
In evince as of version 3.10, evince provides a virtual carot, off by default, which if turned on allows orca to see and interact with document content. I propose that this carot be added,and turned on by default, allowing a similar experience. There is probably code you can carry over from evince to do this, which might need slight modification
##

**Comment by coffeeking** [comment]
just pinging this bug, since atril 1.12 still doesn't have this feature

**Comment by coffeeking** [comment]
Pinging this bug. I'm trying to get joanmeri, the orca developer, to notice this bug so she can provide additional info you guys might find useful.

**Comment by raveit65** [comment]
Carret-navigation is working with 1.20, can we close the report?

**Comment by alexarnaud** [comment]
Le 26/03/2018 à 17:29, raveit65 a écrit :
> Carret-navigation is working with 1.20, can we close the report?

Yes, we can :)! Thanks a lot for the fix.

Best regards,
Alex.
