### ISSUE TITLE
Atril shows blank doc and blank thumbnails on some epubs

### ISSUE THREAD

**Issue by monsta** [mate-desktop/atril#125]
Virtualbox, Debian Jessie, Atril from git master (currently at 1.9.2).
Two virtual machines - one with GTK+2 build of MATE, another with GTK+3 one.

For example, I've downloaded epubs from [here](http://www.nasa.gov/connect/ebooks/global_reach.html) and from [here](http://www.nasa.gov/connect/ebooks/nasas_first_a_detail.html) and tried to view them in Atril. In both cases it showed me the blank document and the blank thumbnails.

![epub-fail](https://cloud.githubusercontent.com/assets/5138986/6164209/e4f2b266-b2ad-11e4-8827-0ba195e3e10d.png)

No error or warning messages appeared in the terminal.
This happens in both GTK+2 and GTK+3 builds.

Well, actually GTK+3 build crashes with `Attempt to unlock mutex that was not locked` once I switch to the thumbnails page, but that's another bug and I'm already planning a fix for it. The main document window is blank anyway.
##

**Comment by rootAvish** [comment]
I tried a GTK+2 build of master, but it's working for me so I can't gather what the problem might be there. Sorry about that. Will try a GTK+3 build and get back on this.

![screenshot-1](https://cloud.githubusercontent.com/assets/5445560/6165285/bcbb61de-b2cc-11e4-9b8c-f1056545ac1a.png)
![screenshot-2](https://cloud.githubusercontent.com/assets/5445560/6165290/be4637cc-b2cc-11e4-8f75-c6c1420eb631.png)

The gtk binary version was 2.10.

**Comment by monsta** [comment]
I have these versions of libs:
```
GLib   2.42.1
GTK+2  2.24.25
GTK+3  3.14.5
WebKit 2.4.8-1
```

**Comment by rootAvish** [comment]
I can read the document with GTK+3 as well, but my library version there was also 3.10. I'll upgrade all my VM's and try it there. Possibly install Jessie itself.

**Comment by monsta** [comment]
BTW, if you'll have GLib >= 2.41, you'll find out that GTK+3 build of Atril crashes with ```Attempt to unlock mutex that was not locked``` on some epubs. Use https://github.com/mate-desktop/atril/pull/128 to fix that.

**Comment by monsta** [comment]
@flexiondotorg @NiceandGently @willysr @infirit
Can you guys please test it in your distros as well? I have 1.9 setup only in Debian Jessie...

**Comment by NiceandGently** [comment]
With f22 atril gtk2 version i have thumbnails with both ebooks.
With f22 atril gtk3 version if thumbnails are enabled in sidebar, atril opens the ebooks --> tries to create the thumbnails --> and atril will close immediately without any abrt (fedora's bugreporting tool) warning.
f22 = GTK+-3.15.x/glib-2.43.x

Same results with f21 (Mate GTK3, latest stable gtk3/glib2), but in i see a gmutex lock issue in terminal.
```
[rave@fedora-21 Jackass]$ atril -f Global_Reach.epub 

** (atril:2599): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

** (WebKitWebProcess:2612): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

Attempt to unlock mutex that was not locked
Aborted (core dumped)
```

**Comment by monsta** [comment]
The mutex issue can be fixed with https://github.com/mate-desktop/atril/pull/128, as I mentioned above. :)

**Comment by monsta** [comment]
@NiceandGently: which version of WebKitGTK+ do you have?

**Comment by NiceandGently** [comment]
atril gtk3 is build with webkitgtk4-devel !
f21 --> webkitgtk4-2.6.5-1.fc21
f22 --> webkitgtk4-2.7.4-6.fc22

opps, i was sleeping.....i will rebuild atril with gmutex fix.

**Comment by NiceandGently** [comment]
If i use only the gmutex fix patch, atril shows me only the thumbnail of the first page, but when i'm  scrolling down/up the sidebar the thumbnail is gone.
![atril-gmutex-fix](https://cloud.githubusercontent.com/assets/961604/6426491/e7096a56-bf5d-11e4-8fda-efb900458dbd.png)
If i use the other patches from your PR too, i see no thumbnails.
Tested in f21.

**Comment by willysr** [comment]
I have thumbnail in Slackware
I build with GTK+2 only since this is what i'm targeting for MATE 1.10

**Comment by monsta** [comment]
@NiceandGently: the warnings are there because I've added emitting a warning when the loading of some part of document fails. :)

**Comment by monsta** [comment]
Looks like I'm the only one to get a blank document (document itself, not the thumbnails)... I get it both with and without https://github.com/mate-desktop/atril/pull/128, so it shouldn't be something in my patch...

**Comment by sc0w** [comment]
time before, I couldnt see thumbnails and doc, and now I can see blank thumbnails, but the doc is ok

(debian atril 1.12 gtk2)

**Comment by raveit65** [comment]
I tested it again, no thumbnails on epel7/f22/f23/f24/  with gtk2/gtk3.
I guess webkit code have changed.
@rootAvish 
can you please take a look into it?

**Comment by sc0w** [comment]
Fixed with https://github.com/mate-desktop/atril/pull/299
