### ISSUE TITLE
Atril triggers BUG in pixman_region32_init_rect: Invalid rectangle passed

### ISSUE THREAD

**Issue by davidwagner** [mate-desktop/atril#130]
When I view https://bugzilla.redhat.com/attachment.cgi?id=998606 with atril, I get the following error:

**\* BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

See https://bugzilla.redhat.com/show_bug.cgi?id=1199329 for full details.
##

**Comment by raveit65** [comment]
I can' reproduce the issue anymore with opening the link with latest atril version in f22.
@davidwagner 
can you please confirm?

**Comment by monsta** [comment]
I confirm this in various versions of Debian or Ubuntu - despite some people saying it's been fixed in some version of poppler (see https://bugs.freedesktop.org/show_bug.cgi?id=71177).
