### ISSUE TITLE
Atril without mate-desktop?

### ISSUE THREAD

**Issue by mazhe** [mate-desktop/atril#146]
Hello,

Before 1.10, it was possible for atril to be built with minimum dependencies, making it a suitable reader for lightweight desktop shells (I was one to push for a atril-lite port in FreeBSD, and recommend it).

This feature seems to have disappeared as atril configure script now fails if pkgconfig do not report mate-desktop and mate icons.

Would it be possible to continue to support the previous build options?

Thank you for your work

**Comment by infirit** [comment]
Already fixed in https://github.com/mate-desktop/atril/commit/2dc3ae141afe190aa646b8062ea561416120d080 :smile:

**Comment by mazhe** [comment]
Oh, thank you very much!
