### ISSUE TITLE
Can't magnify my pdf with atril-Gtk3

### ISSUE THREAD

**Issue by usdanskys** [mate-desktop/atril#148]
I've got a 32.32 × 135.26 inch pdf (file size 40K)of a family tree that opens with a stated magnification of 50%. The magnification spinbox offers me an option of 70%, but selecting 70% does nothing. This appears to be a bug. Evince exhibits the same problem. Both xpdf and the pdf viewer in firefox actually works the way I expected atril and evince to work. I have not checked the performance of atril-Gtk2.

Distro: Fedora 23-branched
atril-1.10.1-11.fc23.x86_64
atril-libs-1.10.1-11.fc23.x86_64
gtk3-3.17.6-1.fc23.x86_64

**Comment by monsta** [comment]
> Evince exhibits the same problem

Which might very well indicate a problem in ```libpoppler-glib``` (used by pdf backend).

**Comment by NiceandGently** [comment]
@usdanskys 
There was a repo issue after rawhide was branched to f23, in result som packages were build with mate gtk2 dependencies : -/
I've rebuild all package today but not bump the versions, ........less work for me :)
I strongly recommend to reinall all mate packages from gtk3 repo.
Note, they have 2 digits in version to be higher as gtk2 packages, ie.
caja-1.10.3-11.fc22.x86_64 --> gtk3
caja-1.10.3-1.fc22.x86_64 --> gtk2

Sorry for that

**Comment by NiceandGently** [comment]
@usdanskys 
can you please test if reinstalling the the whole mate stack fixes the issue?

**Comment by usdanskys** [comment]
Same problem after reinstallation. Also seeing the same problem with evince. Looks like monsta's suggestion that the problem lies with poppler-glib may be correct. I filed a bug against poppler in RH's bugzilla

**Comment by infirit** [comment]
I'll close this for now but please do report back if we need to re-open it.

**Comment by NiceandGently** [comment]
@infirit 
Why closing?
It's not clear that it is poppler-glib related.

**Comment by NiceandGently** [comment]
@usdanskys 
Can you please give us the link to rhbz report?

**Comment by usdanskys** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1258640
I suppose the problem could be in code atril inherited from evince

**Comment by usdanskys** [comment]
Looking at the source code for atril in atril-1.10.2-11.fc23.src.rpm, and although I have little understanding of what I'm looking at, I now believe atril deliberately limits the maximum zoom level, possibly to avoid consuming too much memory. 
1. In the cut-and-paste directory:
   a) ephy-zoom.h has all of the expected zoom levels
   b) ephy-zoom-control.c line 185 appears to create a combo box (without an entry) for zoom levels
2. In the libview directory:
   a) ev-view.c comment beginning at line 5294 regarding cache size might be relevant  
I'm going to leave rh bz 12586490 against poppler-lib for now, although it probably should be filed against evince and atril individually.

**Comment by monsta** [comment]
Ok, that's interesting.
We need to check some things to get more info:
- does evince have the same code mentioned above?
- do atril and evince work fine in stable Fedora releases (e.g. 22)?
- does GTK+2 build of atril work fine?

**Comment by usdanskys** [comment]
1. Code is present in old Gtk2 version of Evince (2.32)
2. Gtk2 atril has same problem
3. Evince 3.6.1 (in Linux Mint 16; I just popped in an old live DVD)
4. Code in evince-3.17.4 libview/ev-view.c around line 7016 set max_scale. Again, it appears to be due to a limited cache size, in this case for view->pixbuf_cache_size.
5. Looking through the code for xpdf, specifically xpdf-3.04/xpdf/XPDFViewer.cc, it uses a (Motif) combobox which has an entry. Also, I can see no obvious imposition of a limit on the zoom level

**Comment by NiceandGently** [comment]
@usdanskys 
https://dl.dropboxusercontent.com/u/49862637/Mate-desktop/SOURCE/atril.tar.xz
Gtk3 test build which include the gsettings key for the cache-page from
https://gist.github.com/infirit/a3abce948ff2b284ac2f
Can you please test?

**Comment by NiceandGently** [comment]
Ok, forget that build, this will break pdf viewing

**Comment by usdanskys** [comment]
Definitely broken :)

**Comment by raveit65** [comment]
@usdanskys 
Here is a new gtk3 build with gsettings key for cache-page from that experimental branch
https://github.com/mate-desktop/atril/commits/dev-page-cache
https://dl.dropboxusercontent.com/u/49862637/Mate-desktop/SOURCE/atril.tar.xz
Please test.

**Comment by usdanskys** [comment]
The new gtk3 build works. Thanks.
