### ISSUE TITLE
Atril side pane activated when opening PDF file for the second time

### ISSUE THREAD

**Issue by avasha** [mate-desktop/atril#149]
The problem relates to Atril 1.8.1 on Debian 8 with the side pane turned off. Side pane has been turned off by default by disabling it and then choosing "Edit" > "Save Current Settings as Default".

Whenever I open a PDF document, which has never been displayed using Atril, it would open with the side pane off - as expected. If I then close it and open it for the second time, the side pane would be turned on. Closing and re-opening would keep the side pane open until I close the file with side pane turned off - as expected. After that, the document would keep the side pane off - as expected. 

So I suspect the problem arises only when opening a document for the second time.

The PDF file locations are on a NFS mounted folder. I observed this behaviour both when launching Atril from Caja 1.8.2 (double-click PDF file) and from MATE Terminal 1.8.1 (command line: atril <filename>).
##

**Comment by victorbriz** [comment]
This is the same problem as described in #145 https://github.com/mate-desktop/atril/issues/145

**Comment by raveit65** [comment]
Works for me with atril-1.20.0.
