### ISSUE TITLE
RFC: Drop embedded MathJax in favor of using distro-packaged one?

### ISSUE THREAD

**Issue by monsta** [mate-desktop/atril#158]
Well, it has been done in Debian [here](http://anonscm.debian.org/cgit/pkg-mate/atril.git/commit/?id=dd1d819fadc8d5410288ec2244c8feaaa3338faa) - as a patch. Can we do the same upstream and drop the excessive amount of source code?

@infirit @flexiondotorg @NiceandGently @willysr @posophe @obache
thoughts?

yes, some of you have already confirmed that MathJax is in your distros, I know :smile:

**Comment by infirit** [comment]
I am not against removing and relying on the distro's packaged version. I am only concerned about distro's that do not have this packaged, slackware was one but then I don't think @willysr enabled epub in atril..

**Comment by flexiondotorg** [comment]
I agree with this proposal.

**Comment by willysr** [comment]
yes, go on with this idea :)
just let me know when it has become a mandatory dep

**Comment by obache** [comment]
I agree  with this idea too.

I don't know whether "/usr/share/javascript/mathjax" is the de facto standard location for MathJax installation or not, but it is better to add a configure option to specify the location (with existence and required version check). I will also avoid potential missing dependency from packaging.

**Comment by posophe** [comment]
I agree too. And don't worry, I'll package it by basing it on Fedora's

**Comment by monsta** [comment]
Ok, there goes https://github.com/mate-desktop/atril/issues/160.

**Comment by raveit65** [comment]
@monsta 
Do i have to include MathJax as runtime require in downstream package?

**Comment by raveit65** [comment]
ok. i see it is already in debian control

**Comment by monsta** [comment]
Yes, runtime dep has to be there - in debian it's ```libjs-mathjax```.
