### ISSUE TITLE
Vector smash protection is enabled

### ISSUE THREAD

**Issue by gungad** [mate-desktop/atril#159]
On Mint 17.2 atril has recently started printing out the following on the console.
Vector smash protection is enabled.
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-0ubuntu1.14.04.1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

I am sure that this is not specific to just atril but it is worrying in that I can find no reason for this to have started recently and can find no answer to why it is happening.
Do any of the developers know where this message is coming from and what is it?

To reproduce the issue simply type in `atril` on the command line.

**Comment by infirit** [comment]
This comes from the new epub back end that uses WebKit.

**Comment by gungad** [comment]
@infirit So is it protection from a stack smashing or heap spraying attack written into Webkit or something else entirely? I have to say, I'm feeling a lot happier about it already.
