### ISSUE TITLE
Improved keyboard interaction

### ISSUE THREAD

**Issue by stefanct** [mate-desktop/atril#17]
a few things i would love to see in atril.
- Correct handling CTRL+left/right when the search pane is active/in focus.
  Currently CTRL+left/right does change the orientation of the pages even if the cursor is in the search pane. I am not sure if this is the default behavior or if i have changed the default shortcuts. In any case i think the key presses should not be swallowed before the search pane gets the change to handle them. I have not looked at the code to see how difficult it is. If the CTRL+left/right keys are indeed the default and you don't want to change the key handling please think about changing the default shortcuts (maybe META/ALT+left/right?)
- ESC should clear selection
  At the moment ESC works to move the focus from the sidepane to the mainpane and to close the in-document search pane (and that should not change), but if that is closed, it has nothing left to do and could be used to deselect any text selection. I guess this should be easy to implement by adding a key listener to the mainpane: if the key event is swallowed by the sidepane or the search pane it won't get activated, but if not it can easily clear the selection.
##

**Comment by raveit65** [comment]
Seems the issue with CTRL+left/right doesn't exists any more?

**Comment by stefanct** [comment]
I am still at 1.12.2 so I cannot tell easily ;) What does ctrl+left/right now when the focus is in the search text field?

**Comment by alexarnaud** [comment]
Le 26/03/2018 à 17:21, raveit65 a écrit :
> Seems the issue with CTRL+left/right doesn't exists any more?

I can confirm that it is correctly fixed in 1.20 on Debian Sid, thanks :)!

Best regards,
Alex.

**Comment by raveit65** [comment]
Thanks for testing.
@stefanct 
We can re-open the report when you updating to a modern MATE version and the issue still exists.
