### ISSUE TITLE
Synchronizing with evince policy

### ISSUE THREAD

**Issue by andreygursky** [mate-desktop/atril#171]
Though it is a mate general question, but since I'm facing it with atril, I'd like to ask it here. Mate should be a good old gnome2, which I love. But I hope it doesn't mean a good old gnome2 with good old gnome2 bugs, does it? There are many bug fixed in evince, which haven't been backported to mate. For a long perspective atril becomes less attractive. Dear maintainers, has this been already discussed? What is the policy of updating atril or there is no at all?

**Comment by monsta** [comment]
We backport upstream fixes from time to time, in all projects. We might miss something though, it happens. Pull requests with fixes are welcome :smile:

**Comment by monsta** [comment]
Ok, I guess the question is answered now?

**Comment by andreygursky** [comment]
Yes, your answer is encouraging, thank you.

On the other hand, there are not a few but dozens fixes to backport. And I'm wondering, whether some script exists, which could help to do decide what evince commits after 2.32 touch that legacy code. So that one could then look, whether these commits should be backported. I wanted to pick up accessibility fixes, but then I thought it would be better to start from the beginning chronologically, since it would be easier not to merge cherry-peeks into mixed code.

And yet another contradiction is dropping support of Win/Mac. Was there any major issue against the support?

**Comment by monsta** [comment]
No, we don't have a script. We pick commits manually.

Win/Mac users have a lot of other similar apps to choose from. Besides, our team is much smaller than gnome's, and simplifying the code is helping us.
