### ISSUE TITLE
atril crash on some epub file

### ISSUE THREAD

**Issue by LaurentBonnaud** [mate-desktop/atril#172]
Hi,

atril crashes when I try to view the attached epub file.  This is in Ubuntu 15.10 with this package version from a MATE PPA:

Package: atril
Version: 1.12.1-1~wily1.0

**Comment by LaurentBonnaud** [comment]
Here is the file to reproduce the crash:

  https://debian-handbook.info/download/stable/debian-handbook.epub

**Comment by monsta** [comment]
Fixed in https://github.com/mate-desktop/atril/commit/064c2a49c1651735033041d19e48a80d8e313e62. We'll make a new bugfix release shortly.

**Comment by monsta** [comment]
@flexiondotorg: 1.12.2 released, please update PPA in Wily :smile:

**Comment by LaurentBonnaud** [comment]
Thank you very much for the fix!

**Comment by monsta** [comment]
Thank @andreygursky, I just merged it :smile:
