### ISSUE TITLE
100 % is not 100 %

### ISSUE THREAD

**Issue by maandree** [mate-desktop/atril#177]
The physical resolution of by monitors is 96 DPI and the system is configured to use 96 DPI. Hence an A4 paper should be displayed on the monitors with the same physical size as a physical A4 paper, but the physical paper is larger. I suspect this has to do with X.org's silly, incorrect calculation of the monitors' physical size (rather than reading the EDID:s.)
##

**Comment by maandree** [comment]
This issue appears one all document viewers.

**Comment by maandree** [comment]
I have located the error: https://github.com/mate-desktop/atril/blob/master/libdocument/ev-document-misc.c#L401

As noted in the documentation for both GTK+ 2 and GTK+ 3, `gdk_screen_get_width_mm` and `gdk_screen_get_height_mm`, may return incorrect values. Which is the case for X.org.

In X, you should only those values if an EDID for the monitor cannot be retrieved. Instead you should read the EDID from the monitor (you may look at https://github.com/maandree/libgamma/blob/master/src/lib/gamma-x-randr.c for how this is done, the function is called `get_edid`, but you may need to read more of the code). The 21st and 22nd bytes in the EDID is used to encode the physical dimension of the monitor, stored in centimetres, (you may look at https://github.com/maandree/libgamma/blob/master/src/lib/edid.c#L80-L81):
```
void get_physical_dimension_mm(unsigned char* edid, size_t* width_mm, size_t* height_mm)
{
  *width_mm = (size_t)(edid[21]) * 10;
  *height_mm = (size_t)(edid[22]) * 10;
}
```

**Comment by maandree** [comment]
Not all monitors have this nice property of the dimension actually being whole centimetres as the EDID would suggest. I did not how the best way to detail with this, but just assuming that they always are is still a better solution than asking X. However, I think, whilst not perfect, you can assume that the width has this property, and then calculate height: `height_mm = width_mm * height_px / width_px`.

**Comment by sc0w** [comment]
- we can use `gdk_monitor_get_width/height_mm` instead `gdk_screen_get_width/height_mm` 

- `gdk_monitor_get_width/height_mm` shows the same value in all resolutions in the same monitor, real values
