### ISSUE TITLE
Synctex in Atril

### ISSUE THREAD

**Issue by antoine-levitt** [mate-desktop/atril#186]
Hi,

I'm having trouble making forward search work using synctex work in atril using dbus, called from auctex (the emacs mode that does latex). The original thread in the auctex mailing list is here: http://thread.gmane.org/gmane.emacs.auctex.bugs/2915. I've tried using the same API as for evince, but that doesn't seem to work. Here's the output from dbus-monitor, showing the SyncView call, which works for evince, but doesn't for atril, apparently. Backwards search works, though. This is with atril 1.12, from linux mint 17.3. Have I missed something? Is there some kind of documentation for atril's dbus API? I took the dbus call from evince, assuming it'd be the same.

 method call sender=:1.72 -> dest=org.mate.atril.Daemon serial=35 path=/org/mate/atril/Daemon; interface=org.mate.atril.Daemon; member=FindDocument
   string "file:///home/antoine/dimer/report/paper.pdf"
   boolean true
method return sender=:1.84 -> dest=:1.72 reply_serial=35
   string ":1.86"
method call sender=:1.72 -> dest=:1.86 serial=36 path=/org/mate/atril/Window/0; interface=org.mate.atril.Window; member=SyncView
   string "/home/antoine/dimer/report/paper.tex"
   struct {
      int32 38
      int32 1
   }
   uint32 0
method return sender=:1.86 -> dest=:1.72 reply_serial=36
##

**Comment by monsta** [comment]
It might be because we have quite old version of synctex here. I'm thinking of making atril depend on distro-provided libsynctex instead. Just need to ask all the maintainers I know about whether it's provided in their distros.

**Comment by giordano** [comment]
Zathura [dropped embedded libsynctex](https://git.pwmt.org/pwmt/zathura/commit/5c60ce41567750eebd6136b0a121b4c2e9c82a06) and now relies on system-provided one, forward/inverse search works like a charm with AUCTeX.  If that's the problem, I think you can drop it safely.

**Comment by igor-liferenko** [comment]
Hi,

Forward search with synctex, because atril does not recognize input file name path in synctex file. This has probably been fixed in evince. The fix should be easily backported to atril.

The matter is, that the command

    pdftex -synctex=1 test.tex

produces this test.synctex.gz file:

    SyncTeX Version:1
    Input:1:/home/user/./test.tex
    ...

If we instead use the command

    pdftex -output-directory `pwd` test.tex

the following test.synctex.gz file is produced:

    SyncTeX Version:1
    Input:1:/home/user/test.tex
    ...

and forward search starts to work.

**Comment by antoine-levitt** [comment]
I see, thanks for the diagnostic! This is a bug on atril's part then, and
should be backported from evince.

Best,

Antoine

**Comment by raveit65** [comment]
For the moment synctex  is updated to 1.18 in master branch.

**Comment by monsta** [comment]
Internal synctex is dropped in master as https://github.com/mate-desktop/atril/pull/411 is merged. External library is used instead.

**Comment by oz123** [comment]
@monsta removing the internal synctex is fine. But what if someone would like to compile atril without synctex support?
Not every one who reads PDF writes latex (in fact I guess the majority of the atril users). 
I would appreciate it this was an option in the build.
