### ISSUE TITLE
Wrong rendering of shadings in PDFs

### ISSUE THREAD

**Issue by MartinThoma** [mate-desktop/atril#188]
I've just created the following pdf:

http://www.martin-thoma.de/bug-report/printer-testpage.pdf

It is rendered correctly by Google Chrome and ImageMagick, but wrong by this PDF viewer:

![Imgur](http://i.imgur.com/S2b5Ob7.png)

See [tex.SE](http://tex.stackexchange.com/q/297702/5645) for the context / other bug reports.
##

**Comment by mabod** [comment]
I tested evince and  okular. They behave like atril. And firefox 45 shows just a pink square.

**Comment by yodalee** [comment]
I ran into this problem at my ArchLinux atril too. But recently, I upgrade whole system and the bug just disappear. I think this problem related to some backend shading library or something else.

**Comment by raveit65** [comment]
I can't reproduce the issue any more with atril-1.18.x with fedora 25/26.
Please mention it here if the issue stiil exists with your distro, i will re-open the report than.
