### ISSUE TITLE
Atril starting mate-screensaver

### ISSUE THREAD

**Issue by mabod** [mate-desktop/atril#192]
Hi,

I am using LMDE2 with cinnamon desktop but have mate installed in parallel. I want to use atril as pdf viewer with cinnamon. But atril always starts the mate-settings-daemon and the mate-screensaver even in the cinnamon environment. So, whenever the screen gets locked I need to authenticate twice: 1st time to the cinnamon screensaver and 2nd time to the mate screensaver. This is annoying. Why is atril starting the mate-screensaver in the first place? This basically makes atril incompatible with other desktop environments. I hope that this is not intentional.

Matthias

**Comment by raveit65** [comment]
@clefebvre 
Can you please take a look into it?

**Comment by monsta** [comment]
Weird... why would it even need a screensaver in the first place?
Ok, we'll take a look at this when we can.

**Comment by monsta** [comment]
Ah... I've already forgot I've ported Clem's fix from xreader to atril in the master branch :smile:
Ok, so it will be fixed in 1.14. I'm not sure if Clem will add it to LMDE though, he'll probably go with more generic xreader (desktop-independent fork of atril). But you'll get the fix either way.

**Comment by tycho-kirchner** [comment]
Ahem, sorry for necroposting, but appenrently Atril 1.20 **still** launches mate-settings-daemon, tested on Debian Buster Xfce. I uninstalled the settings daemon for now and Atril is working fine. Note that I did not expericene the screen-locking-issue though...
Thanks
Tycho
