### ISSUE TITLE
Not all PDF vector graphic elements are printed to a virtual or actual printer

### ISSUE THREAD

**Issue by drws** [mate-desktop/atril#197]
Consider the following input PDF file on v**1.12.2**:

[atril_bug_in.pdf](https://github.com/mate-desktop/atril/files/246145/atril_bug_in.pdf)

If this file is printed on my system on a virtual PDF printer or an actual printer, the following output is produced:

[atril_bug_out.pdf](https://github.com/mate-desktop/atril/files/246147/atril_bug_out.pdf)

As you can see, the file is nothing special. It's made with KiCad and the missing elements are not special in any way. I have tested it on Atril/MATE/Evince/GNOME combinations and Atril seems to be the (only) problem. Also If I try to print the same file with Chromium and choose to "print it using system dialog", the same file is printed without problems to any printer. Can anyone reproduce this nasty bug?
##

**Comment by raveit65** [comment]
Hmm, i see that with both atril/evince with your pdf in print preview dialog.
I don't know nothing about KiCad, but it looks like that the missing part is on another layer.

**Comment by drws** [comment]
No, all of the parts are on the same layer - except for the edge line, which is printed correctly in all cases! As I said, the missing elements are nothing special, the bug is a nasty random type and probably in the Atril/Evince's printing code...

Also confirming that I, too, see the bug already in the print preview. So from @raveit65 Evince test it seems that this bug should probably be fixed upstream? Should I report it to the Evince bugtracker or will you guys handle it?

**Comment by raveit65** [comment]
This would be very helpful if you can file out a report to evince, we're a small team......
Please link the report here.
Thank you

**Comment by drws** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=766152

**Comment by drws** [comment]
The issue was either resolved or might be a duplicate of #498. In any case, it works in 1.26.0 and the issue can be closed.
