### ISSUE TITLE
(pdf) selected text -> right button -> black text

### ISSUE THREAD

**Issue by sc0w** [mate-desktop/atril#211]
debian atril 1.14.1 gtk3

I selected text in a pdf, then right button on the selected text, and shows black text

The epub format doesn't have this bug

**Comment by raveit65** [comment]
gtk+-3.20 --> maybe a theme issue --> but without more information --> i'm clueless ;)

**Comment by sc0w** [comment]
I use the theme TraditionalOk

gtk 3.20.6

I see this only in atril

**Comment by sc0w** [comment]
exactly same than https://github.com/linuxmint/xreader/issues/19 if the window loses focus

**Comment by raveit65** [comment]
A style class .view is missing, here i'm working on it.
For the moment i fixed that in themes for gtk+-3.20
https://github.com/mate-desktop/mate-themes/commit/9b6cd516e0ff7a62eafb6edcf6641df2cb9ddbc2
@lukefromdc
I would do the same for BlackMate.
Here the 'active' bg color isn't defined.
But i don't know which colors you prefer if window is unfocused.

**Comment by lukefromdc** [comment]
Use the same color text as on the normal focussed window. I don't 
generally change text colors on unfocussed windows simply because
multi-window workflows are normal for me and I prefer contents not
to change too much between focussed and not.

**Comment by sc0w** [comment]
@lukefromdc I agree with you

epub format uses the same color text as the normal focussed window

@raveit65 thanks, your commit works, but the color is too light

![before](https://cloud.githubusercontent.com/assets/7734191/16536165/c04d0798-3fee-11e6-83aa-04628585b08f.png)

![later](https://cloud.githubusercontent.com/assets/7734191/16536168/c9fab90c-3fee-11e6-890b-c076b4b5da92.png)

**Comment by raveit65** [comment]
which color?
selected bg?
selected fg?
active bg?
active fg?

**Comment by raveit65** [comment]
btw. ebub is a zip container, here you can change nothing

**Comment by raveit65** [comment]
@sc0w I'm complete passionless with that theme as for my taste it is boring and something from 1884.
...only stupid work for me.
Do you like to maintain it?

**Comment by sc0w** [comment]
this grey color

![grey](https://cloud.githubusercontent.com/assets/7734191/16536942/51e84d66-3ff9-11e6-8e23-8663603c24cd.png)

Is only a suggestion

Thanks for solve this issue quikly :)

**Comment by raveit65** [comment]
Well, i can make the active bg color darker.
But what about the contrast than?

**Comment by sc0w** [comment]
why not the same colors than selected text?

![selectedtext](https://cloud.githubusercontent.com/assets/7734191/16539318/a87bdd3c-403f-11e6-94c3-01606fa6fc29.png)

I think this is the best choice

**Comment by raveit65** [comment]
done !

**Comment by raveit65** [comment]
The real fis for this issue is
https://github.com/mate-desktop/atril/pull/212/commits/1a32d3949a77658c048e07842d7a0361d5e0b4a8
https://github.com/mate-desktop/atril/pull/212/commits/8a9388ebc4deb340a5949cda915d19cf00ddbfc4
