### ISSUE TITLE
Minimum gail version specified is higher than the latest version

### ISSUE THREAD

**Issue by ZannaStar** [mate-desktop/atril#214]
When trying to run `autogen.sh`  and `configure` to compile the most recent (at the time of writing) version I could not resolve a particular dependency issue without resorting to dirty tactics.

At first I got 'no package 'gail' found'. I compiled what seems to be the very latest release of gail, 1.9.4, from [here](http://ftp.gnome.org/pub/GNOME/sources/gail/1.9/). That went fine, and now I got an error saying my gail version wasn't high enough; 1.9.4 is installed, but 2.24 or above is needed. Hmm.

So I checked out configure.ac.

There are these definitions:

```
       GTK_API_VERSION=2.0
       WEBKIT_API_VERSION=1.0
       GAIL_API_VERSION=
       GTK_REQUIRED=2.24.0
       WEBKIT_REQUIRED=2.4.3
```
and then there is this reference:

`PKG_CHECK_MODULES(LIBVIEW, gtk+-$GTK_API_VERSION >= $GTK_REQUIRED gail$GAIL_API_VERSION >= $GTK_REQUIRED`

So I changed `GTK_REQUIRED=2.24.0` to `GTK_REQUIRED=1.0` (having already installed higher GTK versions anyway)

`./autogen.sh` finally got to the end without errors & I was able to `make` etc, and everything is fine.

Was this intended? If so, what should I have done instead of messing with the script?

**Comment by monsta** [comment]
Since 2007, gail is [integrated](https://git.gnome.org/browse/gtk+/commit/?id=a8e6ee33b1ae23caeb1c21218fb2f2a94d945e08) into GTK+, so it's built from its source and has the same version as GTK+. It's usually named ```libgail``` in the distros.
