### ISSUE TITLE
Case sensitive search does not work

### ISSUE THREAD

**Issue by jmssil** [mate-desktop/atril#219]
Case sensitive search does not work in version 1.12.2.

**Comment by monsta** [comment]
I've noticed this, but only in some backends. For example, it doesn't work in PDF but works in ePub.
Looks like it has to be fixed in each backend.

**Comment by monsta** [comment]
https://github.com/mate-desktop/atril/pull/224 fixes it for PDFs. Any other formats where it should be fixed as well?

**Comment by jmssil** [comment]
I only use it for PDF files. I didn't know it could open other files.

**Comment by monsta** [comment]
Ok, I'll close it then since fix for PDFs is merged now. We can reopen it later if some other backends will have to be fixed as well.
