### ISSUE TITLE
Atril crash on pdf (poppler)

### ISSUE THREAD

**Issue by emanuele-f** [mate-desktop/atril#222]
Atril crashes with the following PDF [atril_core_dump.pdf](https://github.com/mate-desktop/atril/files/503505/atril_core_dump.pdf).

As reported in #137, crash occurs in poppler.

System is latest 64 bit archlinux
Poppler version is 0.47.0-1
##

**Comment by monsta** [comment]
Poppler 0.48.0 has been released yesterday. I suggest trying that document with it.

**Comment by monsta** [comment]
So, does it still happen with 0.48.0?

**Comment by emanuele-f** [comment]
Yes, it still happens

**Comment by monsta** [comment]
I just found out there's a patch for poppler to fix this, but looks like it wasn't accepted upstream (yet):
https://bugs.freedesktop.org/show_bug.cgi?id=97870#c3

I only was able to reproduce the crash with atril-thumbnailer (while loading the doc in Atril itself doesn't crash it for me). The patch fixes the crash for good.

**Comment by emanuele-f** [comment]
I've verified the following:
- atril version 1.16.0 (from arch repo) with poppler 0.48.0 *crashes*
- atril version 1.14.2 with poppler 0.47.0-1 does *not* crash (VM)
- atril master branch from github with poppler 0.47.0-1 does *not* crash (VM)
- atril master branch from github with poppler 0.48.0 does *not* crash (VM)

poppler version I indicate is the one installed in the system, although I cannot see libpoppler as a dependency with ldd command. Is poppler statically linked to atril?

**Comment by monsta** [comment]
Indeed, ldd doesn't show poppler to me either. But the dynamic library is the one that's used, that's for sure. Otherwise we wouldn't see ```libpoppler.so.NN``` in the stacktrace.

It seems that the crash is best reproducible with atril-thumbnailer:
```
$ atril-thumbnailer atril_core_dump.pdf some_output_file
```

**Comment by emanuele-f** [comment]
I've just tested with linked patch https://bugs.freedesktop.org/attachment.cgi?id=126698 and I report same experience as yours: atril does not crash, while atri-thumbnailer crashes. The function where it crashes it's still cmsGetColorSpace as before the patch.

**Comment by monsta** [comment]
The patch is finally included upstream (avalable in poppler 0.50), plus a correction for it:
- https://cgit.freedesktop.org/poppler/poppler/commit/?id=9b016440725de086fa87fcbf776e27acee2c01b7
- https://cgit.freedesktop.org/poppler/poppler/commit/?id=1511523450f40b539fb1d58950a907f3712fd5c7

I still can't reproduce the crash of Atril itself, and the patch (with correction) still fixes crash of atril-thumbnailer.

**Comment by monsta** [comment]
Anyway, the issue is (was) in poppler, so please ask upstream developers if there's still some problem with it. Upstream bug report is at https://bugs.freedesktop.org/show_bug.cgi?id=97870.
