### ISSUE TITLE
Atril with GTK 3.22 fails to open cbr and cbz comic files

### ISSUE THREAD

**Issue by acastan** [mate-desktop/atril#225]
Last month Debian Testing upgraded from GTK 3.20 to GTK 3.22. Then Atril 1.14 and Evince 3.21 stopped opening cbr and cbz files. Evince fixed this problem in the upgrade to Evince 3.22 but Atril didn't fix the problem in the upgrade to Atril 1.16.

It seems that the problem is something related to how GTK 3.22 works with mime types. The comics backend is using string equality to match mime-types. This doesn't work when the mime-type has changed, and the old name is now simply an alias. Must use g_content_type_is_a() instead.

To fix the problem Atril developers should change in the file atril/backend/comics/comics-document.c some strcmp (mime_type, ...) with g_content_type_is_a (mime_type, ...) in four places:

http://osdir.com/ml/commits.gnome/2016-09/msg04181.html
https://bugzilla.gnome.org/show_bug.cgi?id=770903

There is a little workaround for normal users that temporary fixes the issue, just editing /usr/lib/x86_64-linux-gnu/atril/3/backends/comicsdocument.atril-backend and add at the end:

MimeType=application/x-cbr;application/x-cbz;application/x-cb7;application/x-cbt;application/x-ext-cbr;application/x-ext-cbz;application/x-ext-cb7;application/x-ext-cbt;application/zip

Excuse my poor english
##

**Comment by acastan** [comment]
Maybe here is some clue:

  http://osdir.com/ml/commits.gnome/2016-09/msg04181.html

  https://bbs.archlinux.org/viewtopic.php?id=217290

**Comment by acastan** [comment]
The patch for Evince in the first link seem to fix the problem in Atril. Have to change in atril/backend/comics/comics-document.c some
  strcmp (mime_type, ...
with
  g_content_type_is_a (mime_type, ...

**Comment by monsta** [comment]
So this is another issue with new MIME types in new versions of shared-mime-info...

Ok, I've adapted Evince fixes in https://github.com/mate-desktop/atril/pull/227. Please test if you can as I don't have any comic books (in both formats) around.
