### ISSUE TITLE
atril crashes on pdf's produced by Mac OS X 10.12 Quartz

### ISSUE THREAD

**Issue by cmichal2** [mate-desktop/atril#234]
A colleague recently bought a shiny new mac, with OS X 10.12. Atril crashes when opening  pdf files he creates. I've attached an example below. I know the pdf is corrupt, running ps2pdf on it yields:

  **** Warning: considering '0000000000 XXXXX n' as a free entry.
   **** Warning: considering '0000000000 XXXXX n' as a free entry.

   **** This file had errors that were repaired or ignored.
   **** The file was produced by: 
   **** >>>> Mac OS X 10.12 Quartz PDFContext <<<<
   **** Please notify the author of the software that produced this
   **** file that it does not conform to Adobe's published PDF
   **** specification.

(Thanks Apple!)
but atril shouldn't crash. Evince doesn't crash, acroread doesn't crash etc.
I've tried this with atril 1.10 (and I think, will double check tomorrow, 1.16).

[CourseWeeksMap(1).pdf](https://github.com/mate-desktop/atril/files/608182/CourseWeeksMap.1.pdf)

**Comment by raveit65** [comment]
No problems with to open this pdf on fedora 24 with atril-1.16.1 compiled with gtk3.

**Comment by cmichal2** [comment]
Interesting. After upgrading my Gentoo box it no longer crashes there, but on an Arch linux machine with atril-1.16.1 and poppler 0.47.0 it still crashes with a segmentation fault.

**Comment by raveit65** [comment]
maybe, this is the problem https://bugzilla.redhat.com/show_bug.cgi?id=1389657
check  for gsettings schemas.
We added a new key with 1.16

**Comment by cmichal2** [comment]
The machine where I still see the crashes does appear to have the new key. I did recompile-schemas, but it seems different.

Backtrace:
Thread 11 "EvJobScheduler" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff8a3d5700 (LWP 980)]
0x00007fff89092670 in cmsGetColorSpace () from /usr/lib/liblcms2.so.2
(gdb) bt
#0  0x00007fff89092670 in cmsGetColorSpace () at /usr/lib/liblcms2.so.2
#1  0x00007fff89407c88 in GfxICCBasedColorSpace::parse(Array*, OutputDev*, GfxState*, int) () at /usr/lib/libpoppler.so.63
#2  0x00007fff894071a0 in GfxColorSpace::parse(GfxResources*, Object*, OutputDev*, GfxState*, int) () at /usr/lib/libpoppler.so.63
#3  0x00007fff8942d200 in Page::loadThumb(unsigned char**, int*, int*, int*) ()
    at /usr/lib/libpoppler.so.63
#4  0x00007fff8978fa57 in poppler_page_get_thumbnail ()
    at /usr/lib/libpoppler-glib.so.8
#5  0x00007fff899cfc0b in  () at /usr/lib/atril/3/backends/libpdfdocument.so
#6  0x00007ffff7553900 in  () at /usr/lib/libatrilview.so.3
#7  0x00007ffff7554d72 in  () at /usr/lib/libatrilview.so.3
#8  0x00007ffff53480d5 in  () at /usr/lib/libglib-2.0.so.0
#9  0x00007ffff4dbc454 in start_thread () at /usr/lib/libpthread.so.0
#10 0x00007ffff4aff7df in clone () at /usr/lib/libc.so.6
(gdb)

**Comment by monsta** [comment]
The stacktrace shows me it's the same issue as https://github.com/mate-desktop/atril/issues/222. You need to patch poppler, see the links to patches in that report or in https://bugs.launchpad.net/bugs/1635812.
