### ISSUE TITLE
Printing documents created in Latex

### ISSUE THREAD

**Issue by doublez13** [mate-desktop/atril#236]
We have a couple hundred machines in a lab at a university, all running CentOS 7.2 with Mate 1.16.
We've noticed that when professors create documents using Latex, they appear completely normal in Atril Document Viewer, but they print all messed up. Most of the text is overlapping

Printing using Okular works as expected. 
We use Cups 1.6 for all printing if that makes a difference.
I'm happy to provide any other information needed!

**Comment by nanxiongchao** [comment]
@doublez13 
Could you provide a file for testing case?
