### ISSUE TITLE
atril must not depend on webkitgtk

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/atril#241]
upstream report:
https://bugzilla.redhat.com/show_bug.cgi?id=1375801

            Bug ID: 1375801
           Summary: atril must not depend on webkitgtk
           Product: Fedora
           Version: rawhide
         Component: atril
          Assignee: chat-to-me@raveit.de
          Reporter: mcatanzaro@gnome.org
        QA Contact: extras-qa@fedoraproject.org
                CC: chat-to-me@raveit.de
            Blocks: 1375784 (webkit1-removal)

The webkitgtk package will be removed from rawhide after Fedora 26 is branched
due to the high number of unfixed security vulnerabilities. You must remove
this dependency or your package will not be present in Fedora 27.

Please refer to [1] for a FAQ on this matter and be advised that for some
packages this may require a substantial amount of work.

[1]
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/AKVB363GFCHHJ5MTHGVYHYT6NLLTF5VM/

Referenced Bugs:

https://bugzilla.redhat.com/show_bug.cgi?id=1375784
[Bug 1375784] Port applications to WebKit2

**Comment by monsta** [comment]
Ah, that's old webkitgtk, it's indeed unsupported upstream these days (at least I heard so). But we already use webkit2gtk here.

```
    PKG_CHECK_MODULES(EPUB, webkit2gtk-4.0 >= $WEBKIT_REQUIRED \
       libxml-2.0 >= $LIBXML_REQUIRED zlib,have_webkit=yes,have_webkit=no)
    if test "x$have_webkit" = "xno"; then
       AC_MSG_NOTICE([Webkit2 4.0 not found, trying 3.0])
       PKG_CHECK_MODULES(EPUB, webkit2gtk-3.0 >= $WEBKIT_REQUIRED \
          libxml-2.0 >= $LIBXML_REQUIRED zlib,have_webkit=yes,have_webkit=no)
    fi
```

**Comment by raveit65** [comment]
omg,
This report was filed out against atril-1.14 (gtk2), see https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/AKVB363GFCHHJ5MTHGVYHYT6NLLTF5VM/
```
$ repoquery --whatrequires --recursive webkitgtk Yum-utils package has been deprecated, use dnf instead. See 'man yum2dnf' for more information. GREYCstoration-gimp-0:2.8-22.fc24.x86_64 atril-0:1.14.1-1.fc24.x86_64 atril-caja-0:1.14.1-1.fc24.x86_64 atril-devel-0:1.14.1-1.fc24.i686 atril-devel-0:1.14.1-1.fc24.x86_64 atril-libs-0:1.14.1-1.fc24.i686 atril-libs-0:1.14.1-1.fc24.x86_64 atril-thumbnailer-0:1.14.1-1.fc24.x86_64
```
So it looks like it that switching to gtk3 in f25 solves the issue.
```
repoquery --whatrequires --recursive webkitgtk | grep atril
```
gives me no result.
From my spec file
```
%if 0%{?fedora}
BuildRequires:  webkitgtk4-devel
%endif
```
I will re-check that with reporter and close the issue if webkitgtk4 is webkit2.

**Comment by raveit65** [comment]
Downstream report is closed as fixed.
