### ISSUE TITLE
Can't change hotkeys using can_change_accels dconf-editor option

### ISSUE THREAD

**Issue by GeneralFailer** [mate-desktop/atril#247]
In the gtk2 version the option worked, but the hotkeys weren't saved on closing.

Version 1.16.1
OS: Arch Linux

**Comment by monsta** [comment]
Yes, but it's not a bug in Atril. It's just another removal of a feature from GTK+3. See the doc [here](https://developer.gnome.org/gtk3/stable/GtkSettings.html#GtkSettings--gtk-can-change-accels).
