### ISSUE TITLE
Ugly toolbar after update from 1.16 to 1.18

### ISSUE THREAD

**Issue by Photon89** [mate-desktop/atril#249]
After today's update from Atril 1.16 to 1.18 (1.17 has been skipped by the repos of Arch Linux), the tool bar has an ugly black border and the elements are dark, see attached screenshots. 
![funktionalableitung pdf_045](https://cloud.githubusercontent.com/assets/1191480/24503628/2c3fd5a4-1553-11e7-8452-92687ef2b496.png)
![funktionalableitung pdf_044](https://cloud.githubusercontent.com/assets/1191480/24503629/2c426b20-1553-11e7-9a1b-f1e538ed9fc5.png)

If the issue is theme related, please point me to some information on how to fix this. Thanks! By the way, using Manjaro Linux with the Vertex Maia theme.

**Comment by raveit65** [comment]
I don't see that with our themes.
Atril use .primary-toolbar as style class which isn't really new in gtk+-3.
Please file out a reports against your theme in your distro.

**Comment by Photon89** [comment]
Thanks for the quick reply, reported a bug against the GTK theme: https://github.com/oberon2007/vertex-maia-themes/issues/5

**Comment by oberon2007** [comment]
@raveit65 could you kindly let me know which themes you are using, so I can look at their settings and hopefully adopt them in our theme.
Thanks in advance!

**Comment by Photon89** [comment]
By the way, the same happens with the original Vertex theme, just checked. I don't know if it is still being maintained (the bugtracker seems quite full...) but maybe it is worth reporting the problem against it as well?

**Comment by raveit65** [comment]
Our Default theme is Menta or BlueMenta from mate-themes.
Sadly some distro maintainer knows it better and set up another default.
https://github.com/mate-desktop/mate-themes/tree/master/desktop-themes
Try
.atril-window .primary-toolbar toolbar .linked button.combo {}
.atril-window .primary-toolbar toolbar entry {}

The tool for debug this called gtk3-inspector.

**Comment by Photon89** [comment]
>  Sadly some distro maintainer knows it better and set up another default.

Isn't one of the advantages of the Linux desktop its diversity? This also holds for theming - actually, in particular for theming, since this is what make distros look different and diverse. Of course this can only work if theming and other tweaks introduced by distributions don't lead to problems, but this is exactly what we are trying to figure out right now, isn't it? This being said, I'm using Atril with Manjaro Xfce, not Manjaro Mate and don't know which theme Manjaro Mate uses...

**Comment by oberon2007** [comment]
Thanks a lot @raveit65 That's very helpful information.
@Photon89 I'm afraid we'r on our own there. upstream vertex-themes seem to have been abandoned for quite a while now, but let me see what I can do! :wink:

**Comment by oberon2007** [comment]
Vertex-Maia is the default Manjaro theme, but Mate not the main official flavour :laughing: 
Whichever way you want to look at it. In any case I think it's great that we are able to collaborate and that Linux is such a huge family already and, yeah, it's a lot about individualism and diversity and of course people like to combine what they like and I think that's great! :smiley: 
Thank you again for your helpful advice. We'll sort it out!

**Comment by Photon89** [comment]
Thanks to both of you, guys, you are awesome! 😄

**Comment by oberon2007** [comment]
The vertex-theme did indeed have ``.primary-toolbar`` class, but not the property ``.primary-toolbar toolbar`` and apparently I need to apply a negative margin to fix the frame.
The top part of vertex is always dark. That's why the buttons and entry box are also dark.
Seems I would need to define a separate style for this entry box and will also need a different button...
