### ISSUE TITLE
Toolbar widgets jump when scrolling from page 9 to page 10

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/atril#275]
#### Expected behaviour
Toolbar widgets should stay in same places as page numbers change 9->10 

#### Actual behaviour
Adding second diget to label from page number GtkEntry  moves the icons right from it, when moving from say,  (9from50) --> (10from50).

#### Steps to reproduce the behaviour
Open any PDF file with more then ten pages in Atril, watch the toolbar while scrolling between page 9 and page 10

#### MATE general version
MATE 1.19 from git master

#### Package version
Locally compiled with GTK 3.22.18

#### Linux Distribution
Debian Unstable

**Comment by raveit65** [comment]
I can use *width-chars* for the GtkLabel,
https://developer.gnome.org/gtk3/stable/GtkLabel.html#gtk-label-set-width-chars
gtk_label_set_width_chars ()
I played a bit with gtk-inspector. Using 11 chars seems to be sufficient for a book with let say 524 pages.
(525 from 524) pages.
So we need to use a value of 14 for bigger books with more than 1000 or 10000 pages to be save.
What do you think?

**Comment by lukefromdc** [comment]
I would advise the larger value: a slightly longer widget will be barely noticable, but jumping on a really big PDF is still a bug.
