### ISSUE TITLE
Find behaviour in presentation mode

### ISSUE THREAD

**Issue by yadayada** [mate-desktop/atril#28]
I am using atril 1.6.0.

When using the find bar in presentation mode, and the entered text is not found on the current page but another, it indicates that "x found on this page" nevertheless. One has to click on the current page content area to switch to the page where the text was actually found.

Also, if there is no highlighting of found occurrences in presentation mode, the "find previous" and "find next" buttons make little sense when there are at least 2 occurrences. So, there should either be highlighting or buttons that switch to the previous or next page with occurrences.

**Comment by monsta** [comment]
Well... according to upstream (Evince) developers, search isn't supposed to work in presentation mode (see [here](https://bugzilla.gnome.org/show_bug.cgi?id=645976#c2)).
Eventually they've turned findbar off there (see [this commit](https://git.gnome.org/browse/evince/commit/?id=79b9e1e0d6efa05a875e0db5407c9b760f3939d4)) and we followed (see https://github.com/mate-desktop/atril/commit/46100f0deb15e2acf100ac7b4f5e2cd27b27e33d).
