### ISSUE TITLE
Atril segfaults when trying to select text from a DjVu file.

### ISSUE THREAD

**Issue by rbrito** [mate-desktop/atril#283]
#### Expected behaviour

Display the document without problems.

#### Actual behaviour

Atril segfaults.

#### Steps to reproduce the behaviour

Just view a djvu file and try to select the text.
 
#### MATE general version

1.18

#### Package version

1.18.1-1

#### Linux Distribution

Debian testing.

#### link to downstream report of your Distribution

I reported directly here.

Here is the backtrace that I get when running under `gdb` with debug symbols installed:

```
(...)
[New Thread 0x7fff80c57700 (LWP 23334)]
[Thread 0x7fff80c57700 (LWP 23334) exited]
[Thread 0x7fff81458700 (LWP 23333) exited]
[Thread 0x7fffdb7fe700 (LWP 23284) exited]

Thread 1 "atril" received signal SIGSEGV, Segmentation fault.
INT_cairo_surface_set_device_scale (surface=0x0, x_scale=1, y_scale=1) at ../../../../src/cairo-surface.c:1714
1714	../../../../src/cairo-surface.c: No such file or directory.
(gdb) bt
#0  INT_cairo_surface_set_device_scale (surface=0x0, x_scale=1, y_scale=1) at ../../../../src/cairo-surface.c:1714
#1  0x00007ffff7553df8 in set_device_scale_on_surface (device_scale=<optimized out>, surface=<optimized out>) at ev-pixbuf-cache.c:256
#2  ev_pixbuf_cache_get_selection_surface (pixbuf_cache=0x555555fa2950, page=page@entry=0, scale=<optimized out>, region=region@entry=0x7fffffffdaf0) at ev-pixbuf-cache.c:1029
#3  0x00007ffff7561388 in merge_selection_region (view=view@entry=0x555555e4dc60, new_list=new_list@entry=0x5555559732e0) at ev-view.c:6045
#4  0x00007ffff7561b4b in compute_selections (view=view@entry=0x555555e4dc60, style=EV_SELECTION_STYLE_GLYPH, start=start@entry=0x555555e4de24, stop=stop@entry=0x555555e4de08) at ev-view.c:6132
#5  0x00007ffff7561d6d in selection_update_idle_cb (view=0x555555e4dc60) at ev-view.c:3794
#6  0x00007ffff06eadd5 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007ffff06eb1a0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007ffff06eb4b2 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007ffff2a260b5 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#10 0x00005555555741e2 in main (argc=<optimized out>, argv=<optimized out>) at main.c:277
(gdb) 
```

This is 100% reproducible on my systems.

**Comment by monsta** [comment]
@raveit65: caused by https://github.com/mate-desktop/atril/commit/31251cb1202aec7cb3bb1addfbbfe55c125f10d7. I'll try the fix from Evince for this.

**Comment by monsta** [comment]
Done in https://github.com/mate-desktop/atril/commit/c3994eadcb093174ac52bd6b62c742bf716f4190.

I suggest always picking commits directly from Evince, like we did before.

**Comment by rbrito** [comment]
Thank you so very much!

**Comment by monsta** [comment]
@raveit65: I'm having problems with picking the fix to 1.18 branch though... too many new commits in master compared to 1.18 😕

**Comment by raveit65** [comment]
@monsta 
carret-navigation + atk changes was a huge job and it isn't finished.
I am guessing applying the fix needs to be done by hand.

**Comment by raveit65** [comment]
Pls test and merge the commit for 1.18 if it works for you.
https://github.com/mate-desktop/atril/commit/4287f17c257eb997c013ce4dcf4a0b82643f1c74

**Comment by raveit65** [comment]
@monsta ^^^^^

**Comment by sc0w** [comment]
debian bug:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=880628

**Comment by sc0w** [comment]
I have tested in 1.18 and it fixes the crash, but it is not possible to select text (I don't have tested in master)

**Comment by raveit65** [comment]
With evince it is possible to select the text of this document.
On the other side i have another djvu where i can't select the text with evince.
https://www.dropbox.com/s/6956e0let6en5h2/1998_browsing.djvu.tar.xz?dl=0

And i get a terminal warning with 1.18 or master if i open both documents.
```
** (atril:13700): CRITICAL **: void webkit_web_view_load_uri(WebKitWebView*, const gchar*): assertion 'uri' failed
```
Why is Webkit involved?
I thought webkitgtk is only neede for epubs.....

Any way, it look like that back porting dvju stuff from evince is needed.
Maybe after 1.20 release......
