### ISSUE TITLE
EPUBs don't work on OpenBSD

### ISSUE THREAD

**Issue by hubslave** [mate-desktop/atril#290]
Observed on atril 1.18.0 from ports on OpenBSD. Downstream report: https://marc.info/?l=openbsd-ports&m=151561080421076&w=2

Trying to read EPUB documents on OpenBSD results in the following log prints (and the misleading GUI error message "File type electronic book document (application/epub+zip) is not supported"):

	atril:/usr/local/lib/atril/3/backends/libepubdocument.so: undefined symbol 'ftello64'
	atril:/usr/local/lib/atril/3/backends/libepubdocument.so: undefined symbol 'fseeko64'
	atril:/usr/local/lib/atril/3/backends/libepubdocument.so: undefined symbol 'fopen64'

	(atril:26401): AtrilDocument-WARNING **: Cannot load specified object

	(atril:26401): AtrilDocument-WARNING **: Cannot load backend 'epubdocument' since file '/usr/local/lib/atril/3/backends/libepubdocument.so' cannot be read.

This is because the BSDs don't have the 64-bit ftello/fseeko/fopen variants. There's already a preprocessor check for FreeBSD to use the plain variants, so expand it to cover the rest of the family:

```
--- a/backend/epub/minizip/ioapi.h
+++ b/backend/epub/minizip/ioapi.h
@@ -50,7 +50,7 @@
 #define ftello64 ftell
 #define fseeko64 fseek
 #else
-#ifdef __FreeBSD__
+#if defined(__OpenBSD__) || defined(__NetBSD__) || defined(__FreeBSD__) || defined(__DragonFly__)
 #define fopen64 fopen
 #define ftello64 ftello
 #define fseeko64 fseeko
```

Ideally, this would be done with a dedicated configure script test, but that is beyond my knowledge of autotools.

With this patch applied, EPUBs can now be opened, but they only show blank pages. The following prints appear on the console:

	(atril:65545): GLib-GObject-WARNING **: value "-538976290" of type 'gint' is invalid or out of range for property 'page' of type 'gint'

	(atril:65545): GLib-GObject-WARNING **: value "-538976290" of type 'gint' is invalid or out of range for property 'page' of type 'gint'

	(atril:65545): GLib-GObject-WARNING **: value "-538976290" of type 'gint' is invalid or out of range for property 'page' of type 'gint'

	(atril:65545): Gtk-WARNING **: Allocating size to EvSidebar 0xd7a580d7f60 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

	(atril:65545): AtrilView-WARNING **: Error loading data from file:///tmp/atril-65545/Metamorphosis-jackson.epubUWLRAZ/OEBPS/front-cover.html: Frame load interrupted

The last one is, I believe, the relevant error, but it comes from the depths of WebKitGTK. I don't know how it might be debugged, since WebKitGTK doesn't compile with debug symbols on BSDs: https://bugs.webkit.org/show_bug.cgi?id=140384

**Comment by monsta** [comment]
Thanks, patch committed.
For blank docs and thumbnails we have https://github.com/mate-desktop/atril/issues/125 still open.
