### ISSUE TITLE
AppStream metadata file found in /usr/share/appdata/.

### ISSUE THREAD

**Issue by sunweaver** [mate-desktop/atril#292]
W: atril-common: appstream-metadata-in-legacy-location usr/share/appdata/atril.appdata.xml
N: 
N:    AppStream metadata file was found in /usr/share/appdata/. The AppStream
N:    XML files should be placed in /usr/share/metainfo/.
N:    
N:    Refer to https://wiki.debian.org/AppStream/Guidelines for details.
N:    
N:    Severity: minor, Certainty: certain
N:    
N:    Check: appstream-metadata, Type: binary

**Comment by monsta** [comment]
Fixed in https://github.com/mate-desktop/atril/commit/2a49c6c2503d017f2ed4c01be561d9fabdf72932, picked to 1.20 branch in https://github.com/mate-desktop/atril/commit/966e36f973f8476d507dceb710e83ec0684dae52.
