### ISSUE TITLE
HiDPI Rendering Scale

### ISSUE THREAD

**Issue by clayfreeman** [mate-desktop/atril#296]
#### Expected behaviour

Atril should render documents to fit their page size with `window-scaling-factor>1`.

#### Actual behaviour

Atril renders the contents of each page of any document at a scale factor of 1, while the page itself is rendered at the correct scale.

#### Steps to reproduce the behaviour

1. Set `window-scaling-factor=2`.
2. Open a PDF to observe the discrepancy.

#### MATE general version

1.20

#### Package version

`master` from git.

#### Linux Distribution

Gentoo Linux

#### Screenshot

![screenshot at 2018-02-28 08-26-25](https://user-images.githubusercontent.com/182658/36792762-18da10cc-1c61-11e8-89f7-1da8b3d6ff33.png)

**Comment by raveit65** [comment]
Confirmed, i see that too with a non-hidpi monitor if using window-scaling-factor=2
Xreader use the same code for hidpi and scales correctly, so i assume it has something to do with latest changes for hidipi with 1.20 or with Gtk_Screen deprecation fixes in 1.19.x.
