### ISSUE TITLE
Crash at atk_object_notify_state_change

### ISSUE THREAD

**Issue by Sam-Tygier** [mate-desktop/atril#302]
#### Expected behaviour
Not crash

#### Actual behaviour
Crash

```Truncated backtrace:
Thread no. 1 (10 frames)
 #0 atk_object_notify_state_change at atkobject.c:1215
 #1 ev_view_accessible_set_page_range at ev-view-accessible.c:574
 #2 view_update_range_and_current_page at ev-view.c:815
 #3 on_adjustment_value_changed at ev-view.c:6676
 #8 emit_value_changed at gtkadjustment.c:349
 #9 adjustment_set_value at gtkadjustment.c:450
 #10 gtk_adjustment_set_value_internal at gtkadjustment.c:545
 #11 gtk_adjustment_set_value at gtkadjustment.c:567
 #12 view_set_adjustment_values at ev-view.c:693
 #13 ev_view_size_allocate at ev-view.c:3749
```

#### Steps to reproduce the behaviour
* Using latexmk which rebuilds a latex file to pdf automatically.
* Pdf is open in atril.
* Atril will refresh each time the PDF is rewriten
* I think if it gets rewritten again during the reload then atril can crash 

#### MATE general version
1.19.3

#### Package version
atril-1.19.6-1.fc27.x86_64

#### Linux Distribution
Fedora 27

#### link to downstream report of your Distribution
https://bugzilla.redhat.com/show_bug.cgi?id=1554134

**Comment by raveit65** [comment]
Is there a reason why you ignore to test the scratch build with a fix at rhbz report?
