### ISSUE TITLE
atril 1.20.1 do not build without webkitgtk

### ISSUE THREAD

**Issue by willysr** [mate-desktop/atril#308]
#### Expected behaviour
Build properly

#### Actual behaviour

```
ev-jobs.c:882:34: error: unknown type name ‘WebKitWebView’
 web_thumbnail_get_screenshot_cb (WebKitWebView  *webview,
                                  ^~~~~~~~~~~~~
ev-jobs.c:883:34: error: unknown type name ‘WebKitLoadEvent’
                                  WebKitLoadEvent event,
                                  ^~~~~~~~~~~~~~~
ev-jobs.c:899:25: error: unknown type name ‘WebKitWebView’
 webview_load_failed_cb (WebKitWebView  *webview,
                         ^~~~~~~~~~~~~
ev-jobs.c:900:25: error: unknown type name ‘WebKitLoadEvent’
                         WebKitLoadEvent event,
                         ^~~~~~~~~~~~~~~
make[3]: *** [Makefile:734: libatrilview_la-ev-jobs.lo] Error 1
make[3]: Leaving directory '/build/tmp/SBo/atril-1.20.1/libview'
make[2]: *** [Makefile:584: all] Error 2
make[2]: Leaving directory '/build/tmp/SBo/atril-1.20.1/libview'
make[1]: *** [Makefile:668: all-recursive] Error 1
make[1]: Leaving directory '/build/tmp/SBo/atril-1.20.1'
make: *** [Makefile:554: all] Error 2
```

#### Steps to reproduce the behaviour

build using this SlackBuild: https://github.com/mateslackbuilds/msb/blob/master/extra/atril/atril.SlackBuild

#### MATE general version

1.20.1

#### Package version

1.20.1

#### Linux Distribution

Slackware

#### link to downstream report of your Distribution

None

**Comment by willysr** [comment]
Even with --disable-epub it still won't build as it still tried to look for webkit2gtk

**Comment by raveit65** [comment]
I just tested the release tarball atril-1.20.1 to build for fedora rawhide with webkit2gtk3-2.20.0-2.fc29
Building for all supported archs by fedora is successful.
See logs from fedora build server https://koji.fedoraproject.org/koji/taskinfo?taskID=25995553
Same for f28 with webkit2gtk3-2.20.0-2.fc28

Is this check for new webkit2gtk correct?
https://github.com/mateslackbuilds/msb/blob/master/extra/atril/atril.SlackBuild#L61

**Comment by willysr** [comment]
hi @raveit65 it seems i wrote the title incorrectly
it was supposed to be **without** webkit2gtk

**Comment by raveit65** [comment]
Why building without?

**Comment by willysr** [comment]
it took a long time to build webkit2gtk and with 2.20, their dependencies increased (again). 
It works with 1.20.0, why not with 1.20.1 ?

**Comment by willysr** [comment]
The webkit2gtk check is correct

on a system with webkit2gtk:
```
willysr@office:~$ pkg-config --exists webkit2gtk-4.0
willysr@office:~$ echo $?
0
```

on a system without webkit2gtk
```
willysr@slack64:~$ pkg-config --exists webkit2gtk-4.0
willysr@slack64:~$ echo $?
1
```

**Comment by raveit65** [comment]
I think we need more checks for webkit in code.
Is it acceptable to build with epub support for the moment?

**Comment by willysr** [comment]
i can postpone building the package for 1.20.1 for now, but the changes has been pushed to git  master in mateslackbuilds.

**Comment by raveit65** [comment]
Ok, i think the issue comes from xreader backport commit.
https://github.com/mate-desktop/atril/commit/bd799f45f16f30284466dd013abecbe35c9d0695#diff-9ef79320d41961244840337c067ca162R879
Seems like
```
 #endif  /* ENABLE_EPUB */
```
is at the wrong place.

> i can postpone building the package for 1.20.1 for now,

Are you building with a intel p1 proc or why you care about build time with webkit2gtk :)

**Comment by willysr** [comment]
Some people prefer to build MATE from source instead of taking other people's package, so adding webkit2gtk just to provide epub support may be an overkill for some people.

So i added the autodetection check for people who are willing to build webkit2gtk.

**Comment by monsta** [comment]
Oops. I completely missed the misplaced `#endif`.
