### ISSUE TITLE
High CPU usage while reading ePub

### ISSUE THREAD

**Issue by balatbn** [mate-desktop/atril#318]
While reading an ePub  document, switch to another application and back (Alt + Tab). If the switched application hides any section of ePub, CPU usage goes to 100% and stays there.

#### Expected behaviour
CPU usage is very high

#### Actual behaviour
No/little CPU usage

#### Steps to reproduce the behaviour
(1) Open ePub document
(2) Switch to another application so that it hides partial/complete ePub
(3) Switch back and CPU usage increases

#### MATE general version
1.20.1

#### Package version
1.20.1

#### Linux Distribution
Solus Mate. Same behavior in Ubuntu mate 18.04

**Comment by balatbn** [comment]
![screenshot at 2018-05-12 17-49-34](https://user-images.githubusercontent.com/6690155/39962794-611555ea-560e-11e8-80a7-af2aa64ab31b.png)

Sample screenshot (high CPU and hiding ePub)

**Comment by raveit65** [comment]
Atril does not use a high cpu load if the window is in the background in fedora 28.
Same for WebKitWebProcess which handle epubs.
![atril-epub](https://user-images.githubusercontent.com/961604/39964339-9b273d7e-5682-11e8-954e-4113bec2c2e4.jpg)
Maybe someone with solus or ubuntu runing like to reproduce it?
```
atril-1.21.0-1.fc28.x86_64
[rave@mother ~]$ rpm -qa webkit2gtk3
webkit2gtk3-2.20.2-1.fc28.x86_64
```

**Comment by balatbn** [comment]
Can you please switch back the window and check again?

**Comment by raveit65** [comment]
I did and i did it again, several times.
Maybe different webkit2gtk version?

**Comment by balatbn** [comment]
You are correct. I checked in fedora mate and I don't see this issue there. Fedora has newer webkit version. I'll raise the issue with distro team. Thanks for the help.
