### ISSUE TITLE
Edited pdf saves to previously used directory, rather than directory in which pdf already exists

### ISSUE THREAD

**Issue by teslasmoustache** [mate-desktop/atril#322]
#### Expected behaviour
1. Open example1.pdf located at ~/Documents/example1/example1.pdf
2. Edit PDF
3. Click "save a copy"
4. File browser opens to directory ~/Documents/example1/example1.pdf. Click "save".
5. Open example2.pdf located at ~/Documents/example2/example2.pdf
6. Edit PDF
7. Click "save a copy"
8. File browser opens to directory ~/Documents/example2/example2.pdf

#### Actual behaviour

5. Open example2.pdf located at ~/Documents/example2/example2.pdf
6. Edit PDF
7. Click "save a copy"
8. File browser opens to directory ~/Documents/example1/example1.pdf

#### Steps to reproduce the behaviour

1. Open one document, make an edit, and save a copy.
2. Open another document from a different directory, make an edit, and click "save a copy"
3. The file browser will open to the location of the first document, rather than the location of the document currently being edited, resulting in inefficient workflow and misplaced documents.

#### MATE general version
1.20.1

#### Package version
1.20.1

#### Linux Distribution
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic

#### link to downstream report of your Distribution

**Comment by rcaridade145** [comment]
@lukefromdc This commit fixes the issue on evince https://gitlab.gnome.org/GNOME/evince/commit/319a6d4922d7a700b10b8aa92c6edf34fdfcec99
