### ISSUE TITLE
[Feature request] support pdf with embedded files

### ISSUE THREAD

**Issue by alete89** [mate-desktop/atril#326]
#### Expected behaviour
Being able to unpack embedded files inside a pdf file

#### Actual behaviour
no way to even know there are emedded files

#### Steps to reproduce the behaviour
have a pdf with files embedded in it like this i found in internet:
[fileAttachment.pdf](https://github.com/mate-desktop/atril/files/2319077/fileAttachment.pdf)

#### MATE general version
1.16.2

> Did you ever test current atril-1.20.x ?

Yes, there isn't an option to see/unpack embedded files in 1.20.2 either.

#### Linux Distribution
debian stretch

My workaround at this time is using pdftk function unpack_files in order to get embedded files.

**Comment by raveit65** [comment]
Did you ever test current atril-1.20.x ?

**Comment by alete89** [comment]
> Did you ever test current atril-1.20.x ?
Thanks. Just edited the issue.

**Comment by vkareh** [comment]
@alete89 - have you found _any_ pdf reader that can display this? I've tried like 5 and none of them do...

**Comment by alete89** [comment]
@vkareh regrettably, only Adobe Reader at the moment. I'm aware that it is not something frequent, but I work in the public administration in Argentina and it turns out that they use this a lot in digital records/proceedings.

**Comment by vkareh** [comment]
@alete89 - oh wow, I see what Adobe is doing there... I looked at some PDF spec implementations, but the only ones I could find were in Java and C#, so it would require quite some work to port this to be compatible with Atril, assuming they even work. A quick search didn't reveal any pdf libraries in C that could do this.

To be honest I don't see this being implemented any time soon. We can leave this issue open, but until someone else creates a library to do this on Linux, or Evince adds this feature that we can backport, we might not be able to pull it off :disappointed:

**Comment by vkareh** [comment]
hmmm... they are the same folks that make xpdf, which doesn't read embedded files either. I just tried out the XpdfReader (which is not open source) and it did not open the attachment from the file posted above... did you try this? Did it work for you?

**Comment by vkareh** [comment]
oh, okay - I just downloaded their xpdf-tools and ran the pdfdetach, it pulled a file named `KSBASE.WQ2` from the file above - is that what it should be?

**Comment by vkareh** [comment]
oh this is great! researching the pdfdetach tool led me to [libpoppler](https://poppler.freedesktop.org/), which is a freedesktop.org library based on xpdf-tools, but fully open source. It actually includes its own version of pdfdetach, which turns out I already had installed.

So I was going to go on a design spree to make libpoppler an optional dependency of Atril and decide where to show the attachments, which I imagined the sidebar would be the right place. Well guess what, I opened Atril to look where would it look good to add and there was already an Attachments sidebar! So I just opened the fileAttachmend.pdf and opened that sidebar, and guess what? The file is showing there!

So we already have this feature apparently :stuck_out_tongue_closed_eyes: 

![screenshot at 2018-08-26 22-12-35](https://user-images.githubusercontent.com/259780/44637062-2a457000-a97d-11e8-8084-7cc8154a1724.png)

**Comment by alete89** [comment]
> oh, okay - I just downloaded their xpdf-tools and ran the pdfdetach, it pulled a file named KSBASE.WQ2 from the file above - is that what it should be?

yes!

> oh this is great! researching the pdfdetach tool led me to libpoppler, which is a freedesktop.org library based on xpdf-tools, but fully open source. It actually includes its own version of pdfdetach, which turns out I already had installed.

I noticed that, somehow I didn't thought it was helpfull. 

> So I was going to go on a design spree to make libpoppler an optional dependency of Atril and decide where to show the attachments, which I imagined the sidebar would be the right place. Well guess what, I opened Atril to look where would it look good to add and there was already an Attachments sidebar! So I just opened the fileAttachmend.pdf and opened that sidebar, and guess what? The file is showing there!

OMG. I feel so ashamed. I swear to god 'I looked for it everywhere'. I guess I didn't.
Thanks for this trip @vkareh :heart:

**Comment by pkzc** [comment]
It might not be true one and a half year ago but today xpdf lists in its sidebar the attached files and can save them to disk.
