### ISSUE TITLE
Atril not using system scroll direction

### ISSUE THREAD

**Issue by piotrkot** [mate-desktop/atril#327]
#### Expected behaviour
In Mouse and Touchpad settings of Xubuntu I have "Reverse scroll direction" option, which configures how scroll is interpreted in applications.

#### Actual behaviour
Setting the above mentioned option does not configure scroll direction for Atril.

#### Steps to reproduce the behaviour
Go to Mouse and Touchpad settings in Xubuntu
Check "Reverse scroll direction" option - verify scrolling direction
Uncheck "Reverse scroll direction" option - verify scrolling direction
Depending on "Reverse scroll direction" option scrolling direction in Atril should be different.

#### MATE general version
Package: mate-desktop                                       

#### Package version
Version: 1.20.1-2ubuntu1

#### Linux Distribution
Xubuntu 18.04

**Comment by rcaridade145** [comment]
@piotrkot  @raveit65  This is not exclusive of Atril. More of a bug with XFCE https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=823195 .

**Comment by piotrkot** [comment]
@rcaridade145 @raveit65 When reported this bug was exclusive of Atril. Applications like terminal, thunar, firefox, text editors, evince were working correctly.
But now Atril works as expected so a bug must have been fixed in some library Atril depends on.
