### ISSUE TITLE
Atril can't open cbr (rar) archives

### ISSUE THREAD

**Issue by terzag** [mate-desktop/atril#341]
On Ubuntu MATE 18.10, Atril can't manage cbr (rar) archives anymore. I get an error message "RAR archive (application/vnd.rar) filetype is not supported" and thumbnails in Caja are not generated. Cbz (zip) archives work fine.

The issue actually already happened with Ubuntu 16.04 and was fixed in Atril 1.16.1. It seems to be back in 1.20.2.

I opened a bug report on [Launchpad](https://bugs.launchpad.net/ubuntu/+source/atril/+bug/1801704), not sure if it's more relevant there or here.

**Comment by acastan** [comment]
The same happened to me with Atril and Evince in Debian testing last month. Stop opening cbr files but still opening cbz files.

Evince fixed it with this patch:

https://gitlab.gnome.org/GNOME/evince/issues/972

**Comment by eli-schwartz** [comment]
This resolution is completely wrong. Atril does NOT support application/vnd.rar, which is the generic RAR format. It exclusively supports application/vnd.comicbook-rar, which is the subclass that specifically has the .cbr extension.

Failure to correctly follow the Freedesktop standard means that atril offers itself as a mimetype handler for all rar files whether they end in the Comic Book Archive format extension or not. Furthermore, the thumbnailer program will offer to thumbnail all RAR files (and file browsers may automatically do so), which is completely wrong.

Downstream bug report: https://bugs.archlinux.org/task/61128
This is resulting in users with very large RAR files that are not comic books, having those files be extracted for attempted thumbnailing.
