### ISSUE TITLE
autom4te.cache consumes 3.1M after  "make distclean"

### ISSUE THREAD

**Issue by Lachlan-A** [mate-desktop/atril#370]
#### Expected behaviour
"make  distclean"  removes all unnecessary generated files

#### Actual behaviour
autom4te.cache remains, consuming 3.1M

There are also lots of Makefile.in  files and assorted things.

(This doesn't bother me -- I'm just letting you know.)

#### Steps to reproduce the behaviour
./autogen.sh
make   # ignore the compile error due to misplaced  #endif
make distclean

#### MATE general version
1.20.1

#### Package version
1.20.1

#### Linux Distribution
Ubuntu MATE

**Comment by raveit65** [comment]
(This doesn't bother me -- pull request is welcome!)

**Comment by Lachlan-A** [comment]
I just noticed that    make maintainer-clean    removes those files, so I won't send a pull request.
