### ISSUE TITLE
Atril use too much memory with PDFs and using max zoom factor!

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/atril#404]
#### Expected behaviour
Not more than 700 - 800MB memory consumption with a 3.5 MB pdf and using max. zoom (more than 800% zoom factor)

#### Actual behaviour
A 3.5 MB pdf use about 2.6 GB memory with max. zoom factor.
Note: Increasing page buffer size to 200 MB do run my box (with 16GB) out of memory. Dangerous!

#### Steps to reproduce the behaviour
1. Use atril from master or 1.22/1.20/1.18 and open this test pdf (or any other) https://www.dropbox.com/s/3sak8kvhb0tq1ph/manual_s25_int_01.pdf?dl=0
2. Watch memory consumption of atril with mate-system-monitor (be careful if you have less memory).
2. Start with 100% zoom and increase zoom factor to max.
3. Reduce zoom factor back to 100 %.

I think we have memory leaks too, but using so much memory is the main problem.

#### MATE general version
Build from master

#### Package version
master / 1.22/1.20/1.18

#### Linux Distribution
Fedora 30

#### link to downstream report of your Distribution
I don`t file out reports against myself ;)

I found out that the issue starts between atril 1.18 and 1.16.
Using atril 1.16.1 (compiled with gtk3 support) doesn't have the issue.
Exactly with this commit ( i back ported that from linuxmint :-/) 

```
[rave@mother atril]$ git bisect good
31251cb1202aec7cb3bb1addfbbfe55c125f10d7 is the first bad commit
commit 31251cb1202aec7cb3bb1addfbbfe55c125f10d7
Author: XXXXXXX <xxxxxx@xxxxxx.xxx>
Date:   Tue Oct 18 15:10:13 2016 -0400

    Add hi-dpi support for main view.
    
    Based on Evince commits 8b965e769808815df9c75a10a0e4972c0904d26a
    and a612f809e4e23d88a661a9604ce84f332189a658.
    
    https://github.com/linuxmint/xreader/commit/4eccf6b

:100644 100644 ba57b81ceeb7f3d2def0f182d2986a8f41576885 36c7fe266c730b66291bf96824d1b78163b0c585 M	configure.ac
:040000 040000 a8cf14becf018152a6b18e56da746c08e289bbec 1f2d1c27be96a3c9536e46a3a517f98195d511a6 M	libview
```

Note: Evince use max 700-800 MB for this document and max zoom.
So, this is the same as atril used before this commit.

**Comment by rcaridade145** [comment]
I believe this issue can be mitigated by this commit on xreader https://github.com/linuxmint/xreader/commit/f0e7e1fa0871a36cfdef13b703dbe27539ba6a65

**Comment by raveit65** [comment]
But this is for fixing text selection https://github.com/linuxmint/xreader/issues/95
Text selection works fine in atril.
Why do you think it fixes the memory issue and did you test it with atril?

**Comment by rcaridade145** [comment]
I have been trying to reduce the memory leaks on Atril and when looking at that code i noticed this  line https://github.com/linuxmint/xreader/blob/master/libview/ev-view.c#L827 `cairo_region_is_empty (text_region) ` which is a validation we don't have.
At my fork - https://github.com/rcaridade145/atril/commit/9d86c5488e870b889f01584360205c1a1edcb623 -  i'm trying to test some backports of memory leak fixes but i'm getting `atril: undefined symbol: ev_document_misc get monitor dpi`

**Comment by Piiit** [comment]
@rcaridade145 Hi, maybe the following commit could help with that issue:  https://github.com/linuxmint/xreader/commit/99927c65306c289e06f693fbf5e75705c61881b4
The goal was to reduce copy/paste code, and have a DPI fallback on failure....

**Comment by raveit65** [comment]
We don't use `ev_document_misc_get_screen_dpi` this in code.
https://github.com/mate-desktop/atril/commit/d387353c800961b730496dc79d2372b2a56875d9

I don't think that xreader commits from 2019 can fix an issue  which was introduce by a xreader commit from 2016 https://github.com/linuxmint/xreader/commit/4eccf6b
Because that means that xreader would have the same issue for 3 years ;)

IHMO, code for `zoom` and page-cache is different in atril compare to evince or xreader.

**Comment by raveit65** [comment]
I just compiled xreader.1.2.0 (first HiDPI version) and it turns out that xviewer doesn't have the issue.
That means that:
1. newer xreader commit aren't related.
2. the problem is caused by older atril commit.
3. xreader HIDPI commits only increase the existing high memory consumption.

I was able to compile
- atril master hard reset to https://github.com/mate-desktop/atril/commit/4b264c661a53e847b958cf6c8913c88a8cc707d5 + https://github.com/mate-desktop/atril/commit/b6a20b77926727af99b39773ee104ffa457c604f + https://github.com/mate-desktop/atril/commit/a134dcdcd6e4b6934c5e8f3cc66ac824d9914d5b + https://github.com/mate-desktop/atril/commit/e4dc06ec2c72f536affda251c98a42dc8355ede3 --> Issue doesn't exists. :smile: 
- atril master hard reset to https://github.com/mate-desktop/atril/commit/00fad2c0d0fcdade570a08f046e85a4558f1fc0c + https://github.com/mate-desktop/atril/commit/b6a20b77926727af99b39773ee104ffa457c604f + https://github.com/mate-desktop/atril/commit/a134dcdcd6e4b6934c5e8f3cc66ac824d9914d5b + https://github.com/mate-desktop/atril/commit/e4dc06ec2c72f536affda251c98a42dc8355ede3 --> High memory load was introduced. :-1: 

https://github.com/mate-desktop/atril/commit/00fad2c0d0fcdade570a08f046e85a4558f1fc0c from was from this PR https://github.com/mate-desktop/atril/pull/240.

**Comment by rcaridade145** [comment]
@raveit65 Can you please take a look at https://gitlab.gnome.org/GNOME/evince/commit/d375c36972ff3a01b7979984b5a1043eb4c807b0 and the original bug https://bugzilla.gnome.org/show_bug.cgi?id=303365

**Comment by raveit65** [comment]
@rcaridade145 
Can you try out this 9 years old commit for yourself, please.
I want to find a solution for this issue first.

**Comment by raveit65** [comment]
@rcaridade145 
Feel free to test https://github.com/mate-desktop/atril/pull/426

**Comment by lukefromdc** [comment]
Just confirmed this here, about to test https://github.com/mate-desktop/atril/pull/426
