### ISSUE TITLE
[Compiling atril from source] Would it be possible to make synctex optional?

### ISSUE THREAD

**Issue by rubyFeedback** [mate-desktop/atril#438]
Hello mate-desktop devs,

I am trying to compile atril 1.24.0 right now.

The configure line shows this error:

    checking for SYNCTEX... no
    configure: error: "SyncTeX support is disabled since library version 1.21 or newer not found"

I looked at configure --help output but could not find a way to disable this.

Would it be possible to make synctex optional? I would be fine with reduced functionality, e. g. just as a simple .pdf file. I may have missed it but right now there appears to be no option in ./configure to allow that (I grepped for "sync" and "tex" but found no results).

**Comment by netrixtardis** [comment]
not sure what distro you are using, but you will need to install libsynctex-dev or texlive packages to compile atril.  refer to commit [fe6a855](https://github.com/mate-desktop/atril/commit/fe6a85533ba08ec7ea3f4cee139e10c76363288a)

**Comment by bsiegert** [comment]
The comments around this say to "use synctex if available". Please make this a configurable option.

Thank you from a package maintainer in pkgsrc :)

**Comment by TimB87** [comment]
I would love to have synctex as an option as well. Not everybody uses tex and needs that with a pdf viewer, right?

**Comment by oz123** [comment]
@rbuj as requested, I rebased the PR against the master. Please review this PR and let me know if this is OK. As @corvus1 mentioned this patch works for 1.23.X, 1.24 and the current master.
