### ISSUE TITLE
slow scrolling for large documents

### ISSUE THREAD

**Issue by ch-f** [mate-desktop/atril#478]
This issue is fixed in evince but not in atril, please see:

https://bugzilla.gnome.org/show_bug.cgi?id=779614
https://gitlab.gnome.org/GNOME/evince/-/commit/c3de8e75d6d0920478af210ba19a2d94b0734917
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=965275

**Comment by ch-f** [comment]
MATE general version

1.24

Package version

1.25.0
Linux Distribution

Linux From Scratch

**Comment by ch-f** [comment]
Pull request [https://github.com/mate-desktop/atril/pull/530](https://github.com/mate-desktop/atril/pull/530) does fix  this issue. Please pick it up.

**Comment by raveit65** [comment]
merged https://github.com/mate-desktop/atril/commit/50d0b23c608020dd1da3fb3e13883941182ec89e
