### ISSUE TITLE
Support Wayland

### ISSUE THREAD

**Issue by wb9688** [mate-desktop/atril#492]
#### Expected behaviour
Atril starts using native Wayland, just like other GTK 3 apps.

#### Actual behaviour
Atril starts using Xwayland. When using `GDK_BACKEND=wayland`, I get the following error: `Cannot parse arguments: Cannot open display:`.

#### Steps to reproduce the behaviour
Open Atril.

#### MATE general version
N/A

#### Package version
1.24.0-1

#### Linux Distribution
Debian unstable

#### link to downstream report of your Distribution
N/A

**Comment by WhyNotHugo** [comment]
XWayland does not support scaling, so, because of this issue, atril render blurry when using hdpi screens.

**Comment by lukefromdc** [comment]
Just confirmed that Atril does not open in Wayfire, again with
Cannot parse arguments: Cannot open display:.
