### ISSUE TITLE
Chapter title wrong in ePub index

### ISSUE THREAD

**Issue by bitfield** [mate-desktop/atril#495]
I self-publish books with ePub, and I've had a report from a reader that the index for my book doesn't display correctly with Atril. It has chapter 2 shown twice, and no chapter 3:

![Screenshot from 2020-10-03 17-23-34](https://user-images.githubusercontent.com/142262/94998074-4463ca80-05a7-11eb-8c28-7358dba41af3.png)

The chapter title _is_ correct, though, in case you were wondering, and it does display normally on all the ePub readers I've tried, including Apple Books and Calibre.

### MATE general version

1.24

#### Package version

1.24.0-1

#### Linux Distribution

Ubuntu Focal

Unfortunately I don't have any way to test this myself, but I include the ePub file here in case it helps you reproduce the issue.

[For The Love of Go - Data.epub.zip](https://github.com/mate-desktop/atril/files/5322056/For.The.Love.of.Go.-.Data.epub.zip)

**Comment by raveit65** [comment]
Cherry-picked to stable branch
https://github.com/mate-desktop/atril/commit/d906764f8333f5f366c61a9b1a8c32a2d8765aa2
