### ISSUE TITLE
Specific PDF is not rendered correctly (partially missing content)

### ISSUE THREAD

**Issue by drws** [mate-desktop/atril#498]
#### Steps to reproduce the behaviour

Consider [this specific PDF](https://www.espressif.com/sites/default/files/1a-esp32_pin_list_en-v0.1.pdf). In Atril, most of the title page content seems to be missing, but not all. The document renders correctly in other PDF viewers (Evince, PDF.js, Master PDF).

#### MATE general version

v1.24.1

#### Package version

v1.24.0

#### Linux Distribution

Arch Linux

**Comment by cwendling** [comment]
Can't reproduce on Debian Unstable with Atril 1.24.0.  I get the same result with this PDF with Atril, Evince, XPDF, ImageMagic (both `display` and `convert thispdf.pdf foo.tiff` and looking at the tiff images) and Firefox's PDF viewer (which I believe is PDF.js).

**Comment by drws** [comment]
Looking at document differences and properties in different viewers, I suspect it is font-related. How does Atril handle missing fonts? In which (font-related) case would text simply not be rendered?

Also, opening the mentioned PDF by running Atril in terminal produces an error line `! SyncTeX Error : No file?` (everything else is the same - file opens, but some of the text is missing).

**Comment by rcaridade145** [comment]
Could this be down to differences to versions of poppler?

**Comment by drws** [comment]
The problem persists for me even with latest poppler `20.12.0`. @cwendling Would you be so kind and check also your version of poppler?

**Comment by cwendling** [comment]
@drws `20.09.0`

**Comment by drws** [comment]
@cwendling I have tried downgrading and it is not the reason. Thank you for all of your help.

While setting up the downgrade, I spotted an immediately-suspicious (and at least in Arch repos optional) package poppler-data, the installation of which has solved the problem. I have reported it [upstream](https://bugs.archlinux.org/task/68899) and am closing this up :)
