### ISSUE TITLE
Unnecessary WebKit Processes

### ISSUE THREAD

**Issue by linuxr21** [mate-desktop/atril#529]
#### Expected behaviour
As I understand it, the WebKit dependency in Atril is only required for reading e-books (epub format). Regular PDF viewing functionality does not depend on WebKit. Therefore, WebKit processes should only be created when the user actually requests to open a file type requiring WebKit to be processed.

#### Actual behaviour
For each PDF document which is opened, Atril creates two WebKit processes, consuming over 80 MiB of memory:
```
linuxr      5414  0.2  2.5 103115832 100528 ?    Sl   12:12   0:12          |   \_ atril /home/linuxr/Desktop/document.pdf
linuxr      5433  0.0  1.1 102551456 45744 ?     SLl  12:12   0:00          |       \_ /usr/lib/aarch64-linux-gnu/webkit2gtk-4.0/WebKitWebProcess 7 28
linuxr      5434  0.0  0.9 85766032 38676 ?      SLl  12:12   0:00          |       \_ /usr/lib/aarch64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess 8 28
```
This seems just a waste of resources and is also bad from a security perspective.

#### Steps to reproduce the behaviour
Open any PDF document with Atril and inspect the created OS processes.

#### MATE general version
1.24.0

#### Package version
1.24.0

#### Linux Distribution
Ubuntu 20.04.2 LTS

**Comment by ke352802081770314** [comment]
I am annoyed by that as well. I am also puzzled that when looking at Task Manager (LXTask 0.1.9), these WebKitWebProcess and WebKitNetworkProcess each (one per atril document I have open) show up as using 81 to 98 GB of VM-Size, which is roughly the same as for the atril process itself. I do not have nearly that much virtual memory so this seems to be an artificial number but it still gives me a dubious feeling.

**Comment by mbkma** [comment]
Confirmed. If an atril window is constructed and if atril is build with epub support, atril will create a new EvWebView which is a subclass of a Gtk WebkitWebView https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebView.html

https://github.com/mate-desktop/atril/blob/ae1c8e7e9e881022bbad8da68b3efcee10268ed0/shell/ev-window.c#L8093

https://github.com/mate-desktop/atril/blob/ae1c8e7e9e881022bbad8da68b3efcee10268ed0/libview/ev-web-view.c#L66
