### ISSUE TITLE
Build issue with 1.26.0 and libsynctex

### ISSUE THREAD

**Issue by jlocash2** [mate-desktop/atril#535]
#### Expected behaviour
Build from source without synctex installed and it builds.

#### Actual behaviour
configure fails because synctex isn't installed.

#### Steps to reproduce the behaviour
Try building it without synctex installed

#### MATE general version
1.26.0

#### Linux Distribution
My own

#### Link to bugreport of your Distribution (requirement)
No bug report.

configure.ac should set enable_synctex=no by default to truly make it optional.

**Comment by mbkma** [comment]
it is optional via `--enable-synctex` (see https://github.com/mate-desktop/atril/blob/master/configure.ac#L374)

**Comment by jlocash2** [comment]
But if synctex is "optional" shouldn't the default be to disable it and enable if requested?
