### ISSUE TITLE
Cannot delete bookmarks

### ISSUE THREAD

**Issue by qwazer** [mate-desktop/atril#552]
#### Expected behaviour
Cannot delete bookmarks

#### Actual behaviour
Can delete bookmarks

#### Steps to reproduce the behaviour

![Screenshot_2021-12-03_09-31-48](https://user-images.githubusercontent.com/3875925/144556447-909144f2-cf8b-4587-8020-1622e23890a0.png)

#### Package version
1.24.0

#### Linux Distribution
debian

**Comment by imrejonk** [comment]
See https://github.com/mate-desktop/atril/issues/220#issuecomment-1140241710
