### ISSUE TITLE
Required file not found

### ISSUE THREAD

**Issue by penthimos** [mate-desktop/atril#567]
I am just attempting to run

./autogen.sh

after doing clone, init, and update, and I get

`configure.ac:713: error: required file 'cut-n-paste/smclient/Makefile.in' not found`

I don't really know what I'm doing or even if this is the place to report this, and it's very possible it's my fault I'm getting this error, so I appreciate your forbearance.

**Comment by rbuj** [comment]
Initialize, fetch and checkout any nested submodules before running `./autogen.sh`:
`git submodule update --init --recursive`

**Comment by penthimos** [comment]
Thank you! I did this. Then `./autogen.sh` gave a new error, "No package 'gtk+-3.0' found".

So I Googled and did `sudo apt-get install build-essential libgtk-3-dev` and then `./autogen.sh` gave
"No package 'gail-3.0' found".

Now I've Googled again and done `apt-get install libatk-adaptor libgail-common` (redundant, as it happens: nothing installed) and `sudo apt-get install libatk-adaptor:i386 libgail-common:i386` and finally `sudo apt-get install gail-3.0`. These both did apparently install something, but I still get the error that it cannot find gail-3.0. It gives the following further advice:

> Consider adjusting the PKG_CONFIG_PATH environment variable if you
> installed software in a non-standard prefix.
> 
> Alternatively, you may set the environment variables LIBVIEW_CFLAGS
> and LIBVIEW_LIBS to avoid the need to call pkg-config.
> See the pkg-config man page for more details.

Thank you again!

**Comment by lukefromdc** [comment]
Are you building for 386 or for 64 bit?  Maybe you are getting ONLY the 32 bit version?
