### ISSUE TITLE
Need Some help..

### ISSUE THREAD

**Issue by CapeCrusader321** [mate-desktop/atril#578]
Hey there can anyone tell me at which location does this app gets installed if we use the tar.xz ??

**Comment by lukefromdc** [comment]
The tar.xz is the SOURCE tarball for building the package. You set the installation prefix
when configuring the built, it defaults to /usr/local but by adding --prefix=/usr to your
build options it will install into /usr. Running ./configure --help in the build directory 
(what you extracted when you untarred the package will give you a long list of options,
including fine-tuning where to install various types of files from the build

**Comment by CapeCrusader321** [comment]
> 

Thanks for the reply, is the git submodule step necesary ??, cant i just use the tar ball directly to begin installation..

**Comment by lukefromdc** [comment]
I do not know if the release tarballs contain the submodules as I don't
have enough experience with subprojects outside of MATE and always
build MATE from git. You can't run git submodule outside of git so I would
imagine a release tarball contains everything you need but I am NOT sure
of this as I do NOT remember what I was using when I had issues with this
building some GNOME packages before MATE used this

**Comment by CapeCrusader321** [comment]
Hey thanks again last question maybe ??
If i add a prefix of /usr while making and installing where will be the executables or command of atril located i mean what would be the output of which atril if  i have done ./autogen.sh --prefix=/usr

**Comment by CapeCrusader321** [comment]
Hey thanks again last question maybe ??
If i add a prefix of /usr while making and installing where will be the executables or command of atril located i mean what would be the output of which atril if  i have done ./autogen.sh --prefix=/usr

**Comment by lukefromdc** [comment]
That will install it into /usr with default subdirectories when make install is run after make
