### ISSUE TITLE
man page omits mentioning epub

### ISSUE THREAD

**Issue by jeremydaw** [mate-desktop/atril#581]
#### Expected behaviour
man page mentions epub where it lists file formats recognized by the program

#### Actual behaviour
man page omits mentioning epub

#### Steps to reproduce the behaviour
man atril

#### MATE general version
n/a

#### Package version
atril-1.26.0-3.fc37.x86_64

#### Linux Distribution
fedora 37

#### Link to bugreport of your Distribution (requirement)
don't know what this means

**Comment by lukefromdc** [comment]
manpages in general here have tended to lag behind feature additions
