### ISSUE TITLE
Does is still make sense to allow such old webkit version in configure.ac?

### ISSUE THREAD

**Issue by oz123** [mate-desktop/atril#586]
I just notice that a recent commit added support for webkit2gtk4.1.

Yet, in configure.ac the required version is minimum of 2.6.0, which was release 9 years ago.

https://webkitgtk.org/2014/09/24/webkitgtk2.6.0-released.html

I believe there is no distro out there that ships such an outdate webkit version. 

Hence, I was wondering if we can update the check to a more recent version:
```
WEBKIT_REQUIRED=2.39.0
```

Also, for clarity, this variable should maybe renamed to : MIN_WEBKIT_REQUIRED.

**Comment by lukefromdc** [comment]
There is no reason to move up a minimum required version of anything unless we are 
using a feature provided by that version and missing in older versions.

**Comment by oz123** [comment]
I see, but is there a reason to particularly specify an obsolete version?
For package maintainers this maybe clear, for end users, it's quite misleading.

**Comment by lukefromdc** [comment]
Only misleading if something likely to be read by someone doing a default
build of the package would appears to specifiy an exact not a minimum
version, and that is not most users.

We will not be unnecessarily "updating" minimum versions of dependencies
beyond those actually depended on to build or run the code
