### ISSUE TITLE
Unable to open .cbr and .cbz files after upgrade to version 1.24.0-1+deb11u1 from 1.24.0-1

### ISSUE THREAD

**Issue by benj-lazaro** [mate-desktop/atril#611]
#### Expected behaviour
Atril opens and reads .cbr and .cbz files either from right-clicking the file from Thunar file manager or from within Atril itself (File -> Open).

#### Actual behaviour
Atril reports an error message "Unable to open document, File type Zip archive (application/zip) is not supported" when opening said files from either of the aforementioned methods.

#### Steps to reproduce the behaviour
1. Rolled back to Atril's previous version 1.24.0-1 using apt
2. Checked and confirmed that the aforementioned files can be opened and its corresponding content read
3. Upgraded to version 1.24.0-1+deb11u1 using apt
4. Checked and confirmed that the files can not be opened, encountered the error message "Unable to open document"

Noticed that the file comicsdocument.atril-backend disappeared from the /usr/lib/x86_64-linux-gnu/atril/3/backends/ directory right after the upgrade. The file was present in the previous version.

This was discovered after an attempt to implement a posted user workaround (https://github.com/mate-desktop/atril/issues/225) but unfortunately it was unable to address the issue.

Attempted to copy the previous version's comicsdocument.atril-backend file to the current version's /usr/lib/x86_64-linux-gnu/atril/3/backends/  but that did not address the issue as well.

#### Package version
Current version:  1.24.0-1+deb11u1
Previous version: 1.24.0-1

#### Linux Distribution
MX Linux 21.3 running on kernel 5.10.0-29-amd64 x86_64 with XFCE 4.18.1

#### Link to bugreport of your Distribution (requirement)
https://bugs.mxlinux.org/index.cgi

**Comment by lukefromdc** [comment]
That sounds like your distro stopped building with comix support as an emergency response to one of the vulnerabilities, then didn't turn it back on after it was fixed.

**Comment by benj-lazaro** [comment]
Thanks.
