### ISSUE TITLE
Textfields improperly highlighted

### ISSUE THREAD

**Issue by wagnered** [mate-desktop/atril#70]
Atril 1.6.2
Fedora 20

Text fields are blacked out: background is same color as foreground.  Printed object presents the same way. Selecting field disables highlighting for editing.
Saving copy after editing causes form to be incorrectly presented in Adobe Reader 9.

The fresh form presents correctly in Linux Adobe Reader 9. Text fields are correctly highlighted and highlighting is removed when text field is selected.  There is a banner with button that disables highlighting when clicked. Printing object correctly presents text fields as highlighted, not blacked out as with Atril.

If the form is first edited with Atril, saved, then  opened with Adobe Reader 9, Adobe Reader then presents form and print object similar to Atril: Text fields are blacked out.

In Atril, the banner with the "Disable Highlighting" button is not displayed. Highlighting  cannot be disabled as with Adobe Reader.

The form can be downloaded from: http://www.dol.wa.gov/forms/420073.pdf

Info that might be relevant:
   Properties of file;
     PDF producer: Adobe PDF library 10.0.1
     PDF version 1.7 Adobe extension level 3 (Acrobat 9.x)
     Application: Adobe InDesign CS6 (Windows)

Ernie D
##

**Comment by monsta** [comment]
I confirm that with at least some fields in that document...

**Comment by raveit65** [comment]
Looks like the issues are fixed with latest versions of atril?

**Comment by monsta** [comment]
Well, with 1.20 I don't see any blackening on text fields in the mentioned document.
