### ISSUE TITLE
Add "libarchive/bsdtar" and "The Unarchiver/unar" support for (rar and others)  files suppor

### ISSUE THREAD

**Issue by coadde** [mate-desktop/atril#79]
Add "libarchive/bsdtar" and "The Unarchiver/unar" support for (rar and others)  files support

bsdtar and unar support rar v3[0][1]

drop gna unrar (deprecated).

[0]http://libarchive.org
[1]http://unarchiver.c3.cx/formats
##

**Comment by monsta** [comment]
So bsdtar support had been added in https://github.com/mate-desktop/atril/commit/d8d4fcd1182e4295cb4307333a4af4ea3e3c75db. Do we need anything else?

**Comment by raveit65** [comment]
merged https://github.com/mate-desktop/atril/commit/77fc877a3985fd9cad49ed0250ab1bdf478e6638
