### ISSUE TITLE
Save form fields

### ISSUE THREAD

**Issue by ghost** [mate-desktop/atril#8]
At evince 2.32.0 I could fill out form fields and save a copy of the pdf-document with the filled out form fields. This was a excellent function.

But atril 1.2.0 (@ Linux Mint 13 MATE Edition) and newer versions of evince have a problem with saving the filled out form fields correct. If I fill out a pdf with form fields and save a copy the data are saved but hidden.
If I open a document with saved form fields, form fields that are empty before seem to be furthermore empty but if I press a field I can see the data. Form fields that filled out with older versions (evince 2.30.0) show the old data, but if I press a field I can see the new data. So on the new data is saved but could not be uses because the form field date is saved hidden.

Thx for your help!

**Comment by monsta** [comment]
Closing as this is working fine in the latest versions.
